# Recent Soils {-#ord-R}

## Concept of the Order {-#con-R}

Recent Soils show only incipient marks of soil-forming processes because of youthfulness, truncation of an older solum or, less commonly, because the soil material is resistant to alteration. Soil formation has been sufficient to develop a distinct topsoil, or as in the case of fine-textured wetland soils, to have ripened sufficiently that fluid layers are not close to the surface. A continuous cover of vascular plants is normally well established. The concept of the order relates predominantly to weak soil development rather than to the length of time of soil formation.

## Correlation {-#cor-R}

The order correlates with the recent soils, but not the gleyed-recent soils, of the NZ Genetic Soil Classification, and includes Entisols and some Inceptisols and Andisols of Soil Taxonomy.

## Occurrence {-#occ-R}

Recent soils occur throughout New Zealand in young landscapes, including alluvial floodplains, unstable steep slopes and slopes mantled by young volcanic ash.

## Accessory Properties of the Order {-#acc-R}

1.  _Weak soil development._ Soil development is mostly confined to topsoils, with B horizon colours and/or pedality occurring in some soils.
2.  _Base saturations are generally high._ Base saturations are usually high except in very humid areas.
3.  _Gravel or rock is not strongly altered._ The alteration status of gravel or rock usually ranges from fresh to moderately weathered.
4.  _Illitic mineralogy._ The soil mineralogy reflects the mineralogy of the parent material. Most Recent Soils have an Illitic mineralogy class except for those formed in tephra which are usually Glassy.
5.  _Deep rooting._ Although textures vary, potential rooting depths are mostly large. Subsurface horizons are usually apedal or weakly pedal and penetration may be limited in some soils.
6.  _Good drainage._ Poorly drained or very poorly drained soils are not included.
7.  _Low P retention._ P retentions are likely to be either low or very low unless the soils occur in mafic materials.
8.  _High fertility._ Natural fertility is generally high.
9.  _Subject to erosion or sedimentation._ The soils are susceptible to erosion and/or sedimentation.

## Summary of Recent Soils Hierarchy {-#sum-R}

```{r}
library(flextable)

table_R <- data.frame(
  'Code' = c('RH',
             rep('RX', 3),
             rep('RS', 4),
             rep('RF', 9),
             rep('RT', 4),
             rep('RO', 6)),
  'Group' = c('Hydrothermal',
              rep('Rocky', 3),
              rep('Sandy', 4),
              rep('Fluvial', 9),
              rep('Tephric', 4),
              rep('Orthic', 6)),
  'Subgroup' = c('Inactive',
                 'Peaty-acidic', 'Acidic', 'Typic',
                 'Mottled', 'Acidic', 'Tephric', 'Typic', 
                 'Mottled-acidic', 'Mottled-saline', 'Saline', 'Mottled-weathered',
                   'Mottled', 'Acidic-weathered', 'Weathered', 'Acidic', 'Typic',
                 'Mottled', 'Buried-pumice', 'Buried-allophanic', 'Typic',
                 'Mottled-pallic', 'Mottled', 'Acidic-weathered', 'Weathered',
                   'Acidic', 'Typic'),
  'Example_Series' = c('-',
                       'pt. Titiraurangi', '-', 'pt. Cadzow',
                       'Waiowhiro', 'Poison Bay', 'Hangatahua', 'pt. Selwyn',
                       'Waiwhetu', 'pt. Motukarara', '-', 'Eweburn', 'Hari Hari',
                         'pt. Manawatu', 'Waimakariri', 'pt. Seaforth', 'pt. Selwyn',
                       '-', 'Matahina', '-', 'Ngauruhoe',
                       '-', '-', '-', '-', '-', 'Barhill')
  )

ft_R <- flextable(table_R)
ft_R <- bold(ft_R, part = 'head')
ft_R <- merge_v(ft_R, 1)
ft_R <- merge_v(ft_R, 2)
ft_R <- valign(ft_R, j = c(1,2), valign = 'top')
ft_R <- bold(ft_R, j = 1)
ft_R <- set_table_properties(ft_R, layout = "autofit")
ft_R <- set_header_labels(ft_R, 
                          'Example_Series' = 'Example Series')
ft_R
```

## Key to Groups of Recent Soils {-#grp-R}

#### __RH__ {-#key-RH}

Recent soils that have either

1.  mean annual soil temperature at 30\ cm from the mineral soil surface of at least 2.5°C more than the mean annual air temperature, or
2.  pH of 4.8 or less in some part of a subsurface horizon at less than 60\ cm from the mineral soil surface.

<div style="text-align: right"> [__HYDROTHERMAL RECENT SOILS__](#RH) </div>

#### __RX__ {-#key-RX}

Other Recent Soils that have a [lithic](#diag-lithc) or [paralithic contact](#diag-plith) either directly beneath the A horizon or have a weathered-B or unconsolidated C horizon that is less than 10\ cm thick.

<div style="text-align: right"> [__ROCKY RECENT SOILS__](#RX) </div>

#### __RS__ {-#key-RS}

Other Recent Soils that are have sand or loamy sand texture and have less than 35% (by volume) gravel, in all horizons between the base of the A horizon and 60\ cm from the mineral soil surface. Lamellae of sandy loam (of insufficient thickness to meet the requirements of an argillic horizon) may be present.

<div style="text-align: right"> [__SANDY RECENT SOILS__](#RS) </div>

#### __RF__ {-#key-RF}

Other Recent Soils that have fluvial features and are not buried by more than 30\ cm of non-fluvial soil material.

<div style="text-align: right"> [__FLUVIAL RECENT SOILS__](#RF) </div>

#### __RT__ {-#key-RT}

Other Recent Soils in tephric soil material from the mineral soil surface to 30\ cm depth or more.

<div style="text-align: right"> [__TEPHRIC RECENT SOILS__](#RT) </div>

#### __RO__ {-#key-RO}

Other Recent Soils.

<div style="text-align: right"> [__ORTHIC RECENT SOILS__](#RO) </div>

## Key to Subgroups of Recent Soils {-#sub-R}

### __RH__ - HYDROTHERMAL RECENT SOILS {-#RH}

Hydrothermal Recent Soils occur adjacent to active hydrothermal areas or areas that were formerly active. The soils indicate active or former hydrothermal activity by either elevated soil temperatures or extreme acidity, respectively.

#### __RHI__ {-#key-RHI}

(only one subgroup recognised).

<div style="text-align: right"> __Inactive Hydrothermal Recent Soils__ </div>

### __RX__ - ROCKY RECENT SOILS {-#RX}
 
Rocky Recent Soils have rock at shallow depths, severely restricting the soil volume available to roots.

#### __RXOA__ {-#key-RXOA}

Rocky Recent Soils that have a [peaty topsoil](#diag-pts) and a pH less than 5.5 in some part below 20\ cm from the mineral soil surface.

<div style="text-align: right"> __Peaty-acidic Rocky Recent Soils__ </div>

#### __RXA__ {-#key-RXA}

Other soils that have pH less than 5.5 in some part below 20\ cm from the mineral soil surface. 

<div style="text-align: right"> __Acidic Rocky Recent Soils__ </div>

#### __RXT__ {-#key-RXT}

Other soils.

<div style="text-align: right"> __Typic Rocky Recent Soils__ </div>

### __RS__ - SANDY RECENT SOILS {-#RS}

Sandy Recent Soils occur in sand deposits which are dominantly aeolian, and sometimes alluvial in origin. Subsurface horizons are sandy.

#### __RSM__ {-#key-RSM}

Sandy Recent Soils that have a [mottled profile form](#diag-mottpf).

<div style="text-align: right"> __Mottled Sandy Recent Soils__ </div>

#### __RSA__ {-#key-RSA}

Other soils that have pH less than 5.5 in some part between 20 and 60\ cm from the mineral soil surface. 

<div style="text-align: right"> __Acidic Sandy Recent Soils__ </div>

#### __RSK__ {-#key-RSK}

Other soils in [tephric soil material](#diag-teph) from the mineral soil surface to 30\ cm depth or more.

<div style="text-align: right"> __Tephric Sandy Recent Soils__ </div>

#### __RST__ {-#key-RST}

Other soils.

<div style="text-align: right"> __Typic Sandy Recent Soils__ </div>

### __RF__ - FLUVIAL RECENT SOILS {-#RF}

Fluvial Recent Soils occur in sediments deposited by flowing water. Many occur on land surfaces that are susceptible to flooding.

#### __RFMA__ {-#key-RFMA}

Fluvial Recent Soils that have both

1.  a [mottled profile form](#diag-mottpf), _and_
2.  pH less than 5.5 in some part between the base of the A horizon and within 60\ cm of the mineral soil surface.

<div style="text-align: right"> __Mottled-acidic Fluvial Recent Soils__ </div>

#### __RFMQ__ {-#key-RFMQ}

Other soils that have both

1.  a [mottled profile form](#diag-mottpf), _and_
2.  have electrical conductivity of 0.8\ mS/cm or more within 60\ cm of the mineral soil surface at some time of the year.

<div style="text-align: right"> __Mottled-saline Fluvial Recent Soils__ </div>

#### __RFQ__ {-#key-RFQ}

Other soils that have electrical conductivity of 0.8\ mS/cm or more within 60\ cm of the mineral soil surface at some time of the year.

<div style="text-align: right"> __Saline Fluvial Recent Soils__ </div>

#### __RFMW__ {-#key-RFMW}

Other soils that have both

1.  a [mottled profile form](#diag-mottpf), _and_
2.  a [weathered-B horizon](#diag-bw) with its lower boundary at 30\ cm or more from the mineral soil surface.

<div style="text-align: right"> __Mottled-weathered Fluvial Recent Soils__ </div>

#### __RFM__ {-#key-RFM}

Other soils that have a [mottled profile form](#diag-mottpf).

<div style="text-align: right"> __Mottled Fluvial Recent Soils__ </div>

#### __RFAW__ {-#key-RFAW}

Other soils that have both

1.  a [weathered-B horizon](#diag-bw) with its lower boundary at 30\ cm or more from the mineral soil surface, _and_
2.  pH less than 5.5 in some part of the subsurface horizons within 60\ cm of the mineral soil surface.

<div style="text-align: right"> __Acidic-weathered Fluvial Recent Soils__ </div>

#### __RFW__ {-#key-RFW}

Other soils that have a [weathered-B horizon](#diag-bw) with its lower boundary at 30\ cm or more from the mineral soil surface.

<div style="text-align: right"> __Weathered Fluvial Recent Soils__ </div>

#### __RFA__ {-#key-RFA}

Other soils that have pH less than 5.5 in some part of subsurface horizons within 60\ cm of the mineral soil surface.

<div style="text-align: right"> __Acidic Fluvial Recent Soils__ </div>

#### __RFT__ {-#key-RFT}

Other soils.

<div style="text-align: right"> __Typic Fluvial Recent Soils__ </div>

### __RT__ - TEPHRIC RECENT SOILS {-#RT}

Tephric Recent Soils occur in unconsolidated sediments of volcanic origin including ash, cinders, lapilli, pumice, and other pyroclastics.

#### __RTM__ {-#key-RTM}

Tephric Recent Soils that have a [mottled profile form](#diag-mottpf).

<div style="text-align: right"> __Mottled Tephric Recent Soils__ </div>

#### __RTBP__ {-#key-RTBP}

Other soils that have a buried soil, with its upper surface within 60\ cm or less from the mineral soil surface that has a B horizon that meets the requirements of [vitric soil material](#diag-vitr).

<div style="text-align: right"> __Buried-pumice Tephric Recent Soils__ </div>

#### __RTBL__ {-#key-RTBL}

Other soils that have a buried soil within 60\ cm or less from the mineral soil surface to the upper surface of the buried soil, and have a B horizon that meets the requirements of [allophanic soil material](#diag-alloph), but not necessarily the requirements for bulk density.

<div style="text-align: right"> __Buried-allophanic Tephric Recent Soils__ </div>

#### __RTT__ {-#key-RTT}

Other soils.

<div style="text-align: right"> __Typic Tephric Recent Soils__ </div>

### __RO__ - ORTHIC RECENT SOILS {-#RO}

Orthic Recent Soils occur on land that is being eroded or has received sediment that has been deposited mainly as a result of slope processes.

#### __ROMP__ {-#key-ROMP}

Other soils that have both

1.  a [mottled profile form](#diag-mottpf), _and_
2.  meets part 2(b) of the requirements for [Pallic Soils](#P).

<div style="text-align: right"> __Mottled-pallic Orthic Recent Soils__ </div>

#### __ROM__ {-#key-ROM}

Orthic Recent Soils that have a [mottled profile form](#diag-mottpf).

<div style="text-align: right"> __Mottled Orthic Recent Soils__ </div>

#### __ROAW__ {-#key-ROAW}

Other soils that have _both_

1.  a [weathered-B horizon](#diag-bw) with its lower boundary at 30\ cm or more from the mineral soil surface, _and_
2.  pH less than 5.5 in some part of the subsurface horizons within 60\ cm of the mineral soil surface.

<div style="text-align: right"> __Acidic-weathered Orthic Recent Soils__ </div>

#### __ROW__ {-#key-ROW}

Other soils that have a [weathered-B horizon](#diag-bw) with its lower boundary at 30\ cm or more from the mineral soil surface.

<div style="text-align: right"> __Weathered Orthic Recent Soils__ </div>

#### __ROA__ {-#key-ROA}

Other soils that have pH less than 5.5 in some part between the base of the A horizon and within 60\ cm of the mineral soil surface.

<div style="text-align: right"> __Acidic Orthic Recent Soils__ </div>

#### __ROT__{-#key-ROT}

Other soils.

<div style="text-align: right"> __Typic Orthic Recent Soils__ </div>
