---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Summary table of letters used in the NZSC {#sec-appendix}

The system for designating the soils consists of letters only. This method has been adopted to make for easier insertion of new subgroups, and to make the codes easier to remember. The following table (@tbl-codes) demonstrates how each code letter has been used in the soil classification, the level at which it has been used, and the meanings.

| Code | Order | Group | Subgroup |
|:----------------|:----------------|:----------------------|:----------------|
| **A** | Anthropic | Acid, Aged-argillic | Abandoned, Acidic, Aged, Artefact |
| **B** | Brown | Ornithogenic | Brown, Buried |
| **C** | Cryic | Cryic | Calcareous, Cemented, Compacted, Concretionary |
| **D** |  | Densipan, Dry-permafrost | Pedal |
| **E** | Melanic | Albic, Melanic | Albic, Melanic |
| **F** |  | Fibric, Fill, Firm, Fluvial | Fill, Firm, Fluid |
| **G** | Gley | Gley, Groundwater-gley | Gley, Gleyed, Granular, Magnesic |
| **H** |  | Humic, Hydrothermal | Humose, Thick |
| **I** |  | Immature, Impeded | Ice-cored, Immature, Inverted-tephric, Ironstone |
| **J** |  | Argillic | Argillic |
| **K** |  |  | Alkaline, Tephric |
| **L** | Allophanic | Allophanic, Laminar, Litter | Allophanic, Laminar |
| **M** | Pumice | Mafic, Mesic, Mixed | Mellow, Mottled |
| **N** | Granular | Nodular | Granular, Nodular, Sodic |
| **O** | Organic | Māori, Orthic | Organic, Orthic, Peaty |
| **P** | Pallic | Perch-gley | Impeded, Pallic, Perch-gleyed, Placic, Pumice, Pumiceous |
| **Q** |  |  | Ortstein, Saline |
| **R** | Recent | Recent, Refuse, Rendzic | Raw, Sulfuric |
| **S** | Semiarid | Sandy | Sandy, Scoriaceous, Soft, Sphagnic |
| **T** |  | Tephric, Truncated | Typic |
| **U** | Ultic | Duric, Sulfuric | Duric, Humus-pan, Sulfidic, Treated-sulfidic, Ultic, Ultra-weathered |
| **V** |  | Vertic | Vertic, Vitric |
| **W** | Raw | Hydric | Weathered, Wet |
| **X** | Oxidic | Fragic, Oxidic, Pan, Rocky | Coarse, Fragic, Oxidic, Pan, Rocky |
| **Y** |  | Yellow | Ultic, Yellow |
| **Z** | Podzol | Solonetzic | Inverted-impeded, Podzol, Podzolic, Silt-mantled |

: NZSC Codes {#tbl-codes .hover tbl-colwidths="\[10,20,35,35\]"}

{{< pagebreak >}}
