---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Brown Soils {#sec-ord-B}

## Concept of the Order {#sec-con-B}

Brown Soils usually contain 2:1 clay minerals. Secondary iron oxides tend to be evenly dispersed through the soil and give a yellowish brown colour to the upper part of the B horizon. Base saturation values are usually moderate to very low.

## Correlation {#sec-cor-B}

The order comprises moderately and weakly weathered yellow-brown earths, yellow-brown sands, southern brown-granular loams and clays, and intergrades from yellow-brown earths to yellow-grey earths, podzols, brown-granular soils, and recent soils, as well as associated steepland soils of the *New Zealand Genetic Soil Classification*. The soils predominantly correlate with the Inceptisols of *Soil Taxonomy* (excluding the suborder of Aquepts), and a few with Entisols.

## Occurrence {#sec-occ-B}

Brown Soils occur in places in which summer dryness is uncommon and that are not waterlogged in winter. They are the most extensive soil order in New Zealand.

## Accessory Properties of the Order {#sec-acc-B}

1.  *Dispersed secondary oxides.* Secondary iron and aluminium oxides are dispersed throughout the soil mass. The soil is brunified (i.e. iron and aluminium oxides form coatings around phyllosilicate clay particles and form bridges between these particles and humus). P retention is moderate to very high.
2.  *Low to moderate base saturation.* Base saturation values in subsoils are usually less than 50%, and KCl-extractable aluminium levels are usually more than 1.5 cmol~c~/kg except where clay contents are relatively low.
3.  *Parent materials are mostly weakly weathered.* [Mafic Brown Soils](#sec-BM) are derived from weakly weathered intermediate or mafic igneous rocks (e.g. phonolite and basalt). Other groups are derived dominantly from quartzo-feldspathic sedimentary rocks (schist and greywacke) or felsic igneous rocks (e.g. rhyolites and granites), or derivatives including loess or aeolian sand. The alteration status of rock fragments or hard rock substrates is usually fresh to moderately weathered and occasionally highly weathered.
4.  *Mica/illite and vermiculite are common clay minerals.* Profiles tend to be mineralogically uniform with depth. Brown Soils cover a wide range of mineralogy classes. Mixed, Illitic, Vermiculitic and Clay-mineralic (involving vermiculite and mica-vermiculite) are common. Some [Allophanic Brown Soils](#sec-BA) have an Amorphic mineralogy class.
5.  *Good Drainage.* No poorly drained or very poorly drained soils are included. Macroporosity is generally moderate (10–14%) except in subsurface horizons of [Firm Brown Soils](#sec-BF).
6.  *Biologically active.* Except in soils that are limited by coldness or acidity, Biogenic features, such as worm casts, are common in topsoils and C/N ratios are moderate to low. The roots of native plants penetrate deeply.
7.  *Relatively stable topsoils.* Aggregates are not readily dispersed.
8.  *Moist climate or low available-water capacity.* Most soils occur in areas with mean annual precipitation of more than 1000 mm. Others have low available-water capacity, or are in sites with low evapotranspiration.

## Summary of Brown Soils Hierarchy {#sec-sum-B}

```{r}
#| label: tbl-B
#| tbl-cap: "Brown Soils"
#| classes: '.plain .hover'

library(gt)

table_B_dat <- data.frame(
  'Code' = c('BL', rep('', 6),
             'BS', rep('', 5),
             'BX', rep('', 1), 
             'BM', rep('', 4),
             'BA', rep('', 5),
             'BF', rep('', 11),
             'BO', rep('', 10)),
  'Group' = c('Allophanic', rep('', 6),
              'Sandy',      rep('', 5),
              'Oxidic',     rep('', 1),
              'Mafic',      rep('', 4),
              'Acid',       rep('', 5),
              'Firm',       rep('', 11),
              'Orthic',     rep('', 10)),
  'Subgroup' = c(
    # BL
    'Mottled', 'Placic', 'Acidic', 'Firm', 'Typic', 'Acidic-pedal', 'Pedal',
    # BS
    'Mottled-placic', 'Mottled', 'Acidic', 'Pallic', 'Pan', 'Typic',
    # BX
    'Mottled', 'Typic',
    # BM
    'Mottled-magnesic', 'Magnesic', 'Mottled', 'Acidic', 'Typic',
    # BA
    'Peaty', 'Mottled-impeded', 'Mottled', 'Cemented', 'Placic', 'Typic',
    # BF
    'Mottled-weathered', 'Mottled-cemented', 'Mottled-pallic', 'Mottled-acidic', 'Mottled',
    'Cemented',  'Placic', 'Allophanic',
    'Weathered', 'Pallic', 'Acidic', 'Typic',
    # BO
    'Mottled-weathered', 'Mottled-pallic', 'Mottled-acidic', 'Mottled', 'Humose',
    'Immature', 'Weathered', 'Pallic', 'Acidic', 'Calcareous', 'Typic'),
  'Example_Series' = c(
    # BL
    '-', '-', 'Tekoa', 'Te Anau', 'Craigieburn', 'Kaiuma', 'Levin', 
    # BS
    '-', 'Awahou', 'Koputaroa', 'Halkett', 'ToeToe', 'Foxton',
    # BX
    '-', '-',
    # BM
    'Croisilles', 'Dun (part)', '-', 'Cargill', 'Pipikaretu', 
    # BA
    'Spenser', 'Lammerlaw', 'Mackley', 'Whiterig', 'Tautuku', 'Carrick',
    # BF
    '-', 'Harwarden', '-', '-', 'Mahinerangi', 'Steward', '-', 'Belmont', '-',
    'Pinelheugh', 'Porteous', 'Waikiwi',
    # BO
    '-', '-', '-', '-', 'Pukaki', 'Grassmere','-', '-', 'Pelorus', '-', 'Ruahine')
  )

table_B <- gt(table_B_dat) |>
  tab_options(
    column_labels.font.weight = 'bold', 
    heading.title.font.weight = 'bold',
    table.align = 'center',
    table.width = '95%'
  ) |>
  cols_label(Example_Series = 'Example Series') |>
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(columns = 1)) |>
  cols_width(Code ~pct(10),  Group ~pct(20), Subgroup ~pct(35))

table_B
```

## Key to Groups of Brown Soils {#sec-grp-B}

#### **BL** {#sec-key-BL .unnumbered}

Brown soils that have within the B or BC horizon a subhorizon that meets the requirements of [allophanic soil material](Diagnostics.qmd#sec-diag-alloph) but not necessarily the requirement for bulk density, and that is 10 cm or more thick and occurs with its upper surface at 60 cm or less from the mineral soil surface.

::: {style="text-align: right"}
[**ALLOPHANIC BROWN SOILS**](#sec-BL)
:::

#### **BS** {#sec-key-BS .unnumbered}

Other Brown Soils that from the base of the A horizon to 60 cm from the mineral soil surface, have sand or loamy sand texture class and less than 35% coarse rock fragments (by volume), in all horizons (except for sandy loam laminations that do not meet the requirements of an [argillic horizon](Diagnostics.qmd#sec-diag-argh)).

::: {style="text-align: right"}
[**SANDY BROWN SOILS**](#sec-BS)
:::

#### **BX** {#sec-key-BX .unnumbered}

Other Brown Soils that in some part of the B horizon within 60 cm of the mineral soil surface, have

1.  A matrix colour value 4 or less, AND
2.  Friable or very friable unconfined failure from very moist to dry soil moisture states, AND
3.  Polyhedral peds with a size of less than 10 mm.

::: {style="text-align: right"}
[**OXIDIC BROWN SOILS**](#sec-BX)
:::

#### **BM** {#sec-key-BM .unnumbered}

Other Brown Soils that, in a subhorizon of the B or BC at 60 cm from the mineral soil surface, or at the base of the B or BC if shallower, have

1.  A matrix colour value 4 or less and moderately or strongly pedal polyhedral peds (20 mm or less in size), OR
2.  5% (by volume) or more coarse rock fragments that consist mainly of mafic or ultramafic rocks (but not tuffaceous greywacke), OR
3.  An exchangeable calcium/magnesium ratio of 0.2 or less and exchangeable magnesium of 1.5 cmol~c~/kg or more.

::: {style="text-align: right"}
[**MAFIC BROWN SOILS**](#sec-BM)
:::

#### **BA** {#sec-key-BA .unnumbered}

Other Brown Soils that have a pH of 4.8 or less in some part between 20 and 60 cm from the mineral soil surface.

::: {style="text-align: right"}
[**ACID BROWN SOILS**](#sec-BA)
:::

#### **BF** {#sec-key-BF .unnumbered}

Other Brown Soils that have a [fragipan](Diagnostics.qmd#sec-diag-fpan), or an apedal subhorizon with a slightly firm or stronger moist soil strength in the B or BC horizon, with an upper boundary within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
[**FIRM BROWN SOILS**](#sec-BF)
:::

#### **BO** {#sec-key-BO .unnumbered}

Other Brown Soils.

::: {style="text-align: right"}
[**ORTHIC BROWN SOILS**](#sec-BO)
:::

## Key to Subgroups of Brown Soils {#sec-sub-B}

### **BL** - ALLOPHANIC BROWN SOILS {#sec-BL .unnumbered}

Allophanic Brown Soils occur in soils that have a horizon with properties dominated by the presence of nanocrystalline minerals and/or aluminium-humus complexes. Such horizons are weak in strength, sensitive, and have low bulk density. They occur in quartzo-feldspathic and tuffaceous (greywacke) sandstone and argillite, and in tephra-derived parent materials.

#### **BLM** {#sec-key-BLM .unnumbered}

Allophanic Brown Soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Allophanic Brown Soils**
:::

#### **BLP** {#sec-key-BLP .unnumbered}

Other soils that have a [placic horizon](Diagnostics.qmd#sec-diag-plac).

::: {style="text-align: right"}
**Placic Allophanic Brown Soils**
:::

#### **BLA** {#sec-key-BLA .unnumbered}

Other soils that have, in some part of the B or BC horizon to 60 cm from the mineral soil surface, BOTH

1.  An earthy structure, or, if weakly pedal or apedal, a bulk density of the fine-earth fraction less than 1.1 Mg/m^3^, AND
2.  pH less than 5.5.

::: {style="text-align: right"}
**Acidic Allophanic Brown Soils**
:::

#### **BLF** {#sec-key-BLF .unnumbered}

Other soils that have BOTH

1.  In some part of the B horizon to 60 cm from the mineral soil surface, an earthy structure, or, if weakly pedal or apedal, a bulk density of the fine-earth fraction less than 1.1 Mg/m^3^, AND
2.  An underlying layer that meets the requirements of a [fragipan](Diagnostics.qmd#sec-diag-fpan) except for pedality, or an apedal subhorizon with a slightly firm or stronger moist soil strength, with an upper boundary within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Firm Allophanic Brown Soils**
:::

#### **BLT** {#sec-key-BLT .unnumbered}

Other soils that have, in some part of the B or BC horizon to 60 cm depth from the mineral soil surface, an earthy structure, or, if weakly pedal or apedal, a bulk density of the fine-earth fraction less than 1.1 Mg/m^3^.

::: {style="text-align: right"}
**Typic Allophanic Brown Soils**
:::

#### **BLAD** {#sec-key-BLAD .unnumbered}

Other soils that have pH less than 5.5 in some part of the B or BC horizon at 60 cm or less from the mineral soil surface.

::: {style="text-align: right"}
**Acidic-pedal Allophanic Brown Soils**
:::

#### **BLD** {#sec-key-BLD .unnumbered}

Other soils.

::: {style="text-align: right"}
**Pedal Allophanic Brown Soils**
:::

### **BS** - SANDY BROWN SOILS {#sec-BS .unnumbered}

Sandy Brown Soils occur in sand deposits which are usually of aeolian origin, but may also be of alluvial origin. Subsurface horizons have a sand or loamy sand texture class.

#### **BSMP** {#sec-key-BSMP .unnumbered}

Sandy Brown Soils that have BOTH

1.  A [placic horizon](Diagnostics.qmd#sec-diag-plac), AND
2.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled-placic Sandy Brown Soils**
:::

#### **BSM** {#sec-key-BSM .unnumbered}

Other soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Sandy Brown Soils**
:::

#### **BSA** {#sec-key-BSA .unnumbered}

Other soils that have pH less than 5.5 in some part of the B or BC horizon, to its base, or to 60 cm from the mineral soil surface (whichever is shallower).

::: {style="text-align: right"}
**Acidic Sandy Brown Soils**
:::

#### **BSP** {#sec-key-BSP .unnumbered}

Other soils that have EITHER

1.  An [argillic horizon](Diagnostics.qmd#sec-diag-argh) composed of lamellae, OR
2.  An [eluvial horizon](Diagnostics.qmd#sec-diag-eluvh), or skeletans as apparent segregations of relatively higher colour value in B or BC horizons ("two-tone").

::: {style="text-align: right"}
**Pallic Sandy Brown Soils**
:::

#### **BSX** {#sec-key-BSX .unnumbered}

Other soils that have either a [placic horizon](Diagnostics.qmd#sec-diag-plac) or [ortstein-pan](Diagnostics.qmd#sec-diag-opan).

::: {style="text-align: right"}
**Pan Sandy Brown Soils**
:::

#### **BST** {#sec-key-BST .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Sandy Brown Soils**
:::

### **BX** - OXIDIC BROWN SOILS {#sec-BX .unnumbered}

Oxidic Brown Soils occur in strongly weathered soil materials similar to those of [Oxidic Soils](Key-to-Orders.qmd#sec-X) except that [Oxidic Brown Soils](#sec-BX) are less weathered and thus have more reserve magnesium. They usually occur in association with [Oxidic Soils](Key-to-Orders.qmd#sec-X), [Ultic Soils](Key-to-Orders.qmd#sec-U) or [Granular Soils](Key-to-Orders.qmd#sec-N) but on younger land surfaces.

#### **BXM** {#sec-key-BXM .unnumbered}

Oxidic Brown Soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Oxidic Brown Soils**
:::

#### **BXT** {#sec-key-BXT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Oxidic Brown Soils**
:::

### **BM** - MAFIC BROWN SOILS {#sec-BM .unnumbered}

Mafic Brown Soils occur in soil materials weathered from ultramafic, mafic or intermediate igneous rocks or tuffs. They have relatively high proportions of dark magnesium and iron-rich (mafic) silicate minerals, and have relatively large contents of iron oxides.

#### **BMMG** {#sec-key-BMMG .unnumbered}

Mafic Brown Soils that have BOTH

1.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf), AND
2.  *Either*
    (a) 5% (by volume) or more coarse rock fragments consisting mainly of ultramafic rocks, *or*
    (b) have an exchangeable calcium/magnesium ratio of 0.2 or less in some part of the B or BC horizon to 60 cm from the mineral soil surface.

::: {style="text-align: right"}
**Mottled-magnesic Mafic Brown Soils**
:::

#### **BMG** {#sec-key-BMG .unnumbered}

Other soils that have EITHER

1.  5% (by volume) or more coarse rock fragments consisting mainly of ultramafic rocks, OR
2.  Have an exchangeable calcium/magnesium ratio of 0.2 or less in some part of the B or BC horizon to 60 cm from the mineral soil surface.

::: {style="text-align: right"}
**Magnesic Mafic Brown Soils**
:::

#### **BMM** {#sec-key-BMM .unnumbered}

Other soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Mafic Brown Soils**
:::

#### **BMA** {#sec-key-BMA .unnumbered}

Other soils that have pH less than 5.5 in some part of the B or BC horizon to 60 cm from the mineral soil surface.

::: {style="text-align: right"}
**Acidic Mafic Brown Soils**
:::

#### **BMT** {#sec-key-BMT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Mafic Brown Soils**
:::

### **BA** - ACID BROWN SOILS {#sec-BA .unnumbered}

Acid Brown Soils are strongly or extremely acidic soils, many of which occur in very moist or cold mountain environments. Many have a [placic horizon](Diagnostics.qmd#sec-diag-plac).

#### **BAO** {#sec-key-BAO .unnumbered}

Acid Brown Soils that have a [peaty topsoil](Diagnostics.qmd#sec-diag-pts).

::: {style="text-align: right"}
**Peaty Acid Brown Soils**
:::

#### **BAMP** {#sec-key-BAMP .unnumbered}

Acid Brown Soils that have BOTH

1.  A [placic horizon](Diagnostics.qmd#sec-diag-plac) or [ortstein-pan](Diagnostics.qmd#sec-diag-opan) at 60 cm or less from the mineral soil surface, AND
2.  A [mottled](Diagnostics.qmd#sec-diag-mottpf) or [gley profile form](Diagnostics.qmd#sec-diag-gleypf) in combination with [perch-gley features](Diagnostics.qmd#sec-diag-pgley).

::: {style="text-align: right"}
**Mottled-impeded Acid Brown Soils**
:::

#### **BAM** {#sec-key-BAM .unnumbered}

Other soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Acid Brown Soils**
:::

#### **BAC** {#sec-key-BAC .unnumbered}

Other soils that have a horizon that is cemented to the degree that it is at least weakly indurated, within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Cemented Acid Brown Soils**
:::

#### **BAP** {#sec-key-BAP .unnumbered}

Other soils with a [placic horizon](Diagnostics.qmd#sec-diag-plac).

::: {style="text-align: right"}
**Placic Acid Brown Soils**
:::

#### **BAT** {#sec-key-BAT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Acid Brown Soils**
:::

### **BF** - FIRM BROWN SOILS {#sec-BF .unnumbered}

Firm Brown Soils have an apedal subsurface horizon with a slightly firm or stronger moist soil strength which shares some of the characteristics of a [fragipan](Diagnostics.qmd#sec-diag-fpan) or an [ortstein-pan](Diagnostics.qmd#sec-diag-opan). The soils occur on relatively stable sites and are most commonly on flat, rolling or moderately hilly slopes.

#### **BFMW** {#sec-key-BFMW .unnumbered}

Other soils that have BOTH

1.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf), AND
2.  Rock fragments that in the majority are weathered to the extent that they may easily be broken by hammer or spade.

::: {style="text-align: right"}
**Mottled-weathered Firm Brown Soils**
:::

#### **BFMC** {#sec-key-BFMC .unnumbered}

Other soils that have BOTH

1.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf), AND
2.  A horizon that is cemented to the degree that it is at least weakly indurated, within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Mottled-cemented Firm Brown Soils**
:::

#### **BFMP** {#sec-key-BFMP .unnumbered}

Other soils that have BOTH

1.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf), AND
2.  That have in some part of the B or BC horizon to 90 cm in from the mineral soil surface, either matrix hue of 2.5Y or yellower or matrix hue of 10YR and chroma 4 or less with *either*
    (a) no more than a slight reaction to the [reactive-aluminium test](Diagnostics.qmd#sec-diag-naf), *or*
    (b) a [cutanic horizon](Diagnostics.qmd#sec-diag-cuth), *or*
    (c) P-retention less than 30%.

::: {style="text-align: right"}
**Mottled-pallic Firm Brown Soils**
:::

#### **BFMA** {#sec-key-BFMA .unnumbered}

Firm Brown Soils that have BOTH

1.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf), AND
2.  pH less than 5.5 in some part between the base of the A horizon and within 60 cm of the mineral soil surface.

::: {style="text-align: right"}
**Mottled-acidic Firm Brown Soils**
:::

#### **BFM** {#sec-key-BFM .unnumbered}

Other Soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Firm Brown Soils**
:::

#### **BFC** {#sec-key-BFC .unnumbered}

Other soils that have a horizon that is cemented to the degree that it is at least weakly indurated, within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Cemented Firm Brown Soils**
:::

#### **BFF** {#sec-key-BFF .unnumbered}

Other soils that have a [placic horizon](Diagnostics.qmd#sec-diag-plac).

::: {style="text-align: right"}
**Placic Firm Brown Soils**
:::

#### **BFL** {#sec-key-BFL .unnumbered}

Other soils that have P retention 85% or more, or a strong reaction to the [reactive-aluminium test](Diagnostics.qmd#sec-diag-naf), in some part of the B or BC horizon to 90 cm or less from the mineral soil surface.

::: {style="text-align: right"}
**Allophanic Firm Brown Soils**
:::

#### **BFW** {#sec-key-BFW .unnumbered}

Other soils in which the majority of the coarse rock fragments are weathered to the extent that clasts may easily be broken by hammer or spade.

::: {style="text-align: right"}
**Weathered Firm Brown Soils**
:::

#### **BFP** {#sec-key-BFP .unnumbered}

Other soils that have in some part of the B or BC horizon to 90 cm from the mineral soil surface, EITHER

1.  Matrix hue of 2.5Y or yellower, OR
2.  Matrix hue of 10YR and chroma 4 or less with *either*
    (a) no more than a slight reaction to the [reactive-aluminium test](Diagnostics.qmd#sec-diag-naf), *or*
    (b) a [cutanic horizon](Diagnostics.qmd#sec-diag-cuth), *or*
    (c) P-retention less than 30%.

::: {style="text-align: right"}
**Pallic Firm Brown Soils**
:::

#### **BFA** {#sec-key-BFA .unnumbered}

Other soils that have in some part of the B or BC horizon above the apedal horizon with a slightly firm or stronger unconfined strength class when moist, EITHER

1.  pH less than 5.5, OR
2.  A subhorizon with 10% or more humus or humus-clay coatings of moist colour value 4 or less or colour value 5 and chroma 3.

::: {style="text-align: right"}
**Acidic Firm Brown Soils**
:::

#### **BFT** {#sec-key-BFT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Firm Brown Soils**
:::

### **BO** - ORTHIC BROWN SOILS {#sec-BO .unnumbered}

Orthic Brown Soils have B horizon peds or have weak or very weak soil strength to depth. They most commonly occur on hilly or steep slopes, or on Holocene land surfaces.

#### **BOMW** {#sec-key-BOMW .unnumbered}

Orthic Brown Soils that have BOTH

1.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf), AND
2.  Rock fragments that in the majority are weathered to the extent that they may easily be broken by hammer or spade.

::: {style="text-align: right"}
**Mottled-weathered Orthic Brown Soils**
:::

#### **BOMP** {#sec-key-BOMP .unnumbered}

Other soils that have BOTH

1.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf), AND
2.  In some part of the B or BC horizon to 90cm in from the mineral soil surface, either matrix hue of 2.5Y or yellower or matrix hue of 10YR and chroma 4 or less with *either*
    (a) no more than a slight reaction to the [reactive-aluminium test](Diagnostics.qmd#sec-diag-naf), *or*
    (b) a [cutanic horizon](Diagnostics.qmd#sec-diag-cuth), *or*
    (c) P-retention less than 30%.

::: {style="text-align: right"}
**Mottled-pallic Orthic Brown Soils**
:::

#### **BOMA** {#sec-key-BOMA .unnumbered}

Other soils that have BOTH

1.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf), AND
2.  pH less than 5.5 in some part between the base of the A horizon and within 60 cm of the mineral soil surface.

::: {style="text-align: right"}
**Mottled-acidic Orthic Brown Soils**
:::

#### **BOM** {#sec-key-BOM .unnumbered}

Other soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Orthic Brown Soils**
:::

#### **BOH** {#sec-key-BOH .unnumbered}

Other soils that have BOTH

1.  Colour value of the matrix 4 or less and hue 2.5Y or redder, or 10% or more coatings of colour value 4 or less in the greater part of the B horizon, AND
2.  10% or less clay within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Humose Orthic Brown Soils**
:::

#### **BOI** {#sec-key-BOI .unnumbered}

Other soils that have EITHER

1.  A buried A horizon within 120 cm of the mineral soil surface, OR
2.  A [weathered-B horizon](Diagnostics.qmd#sec-diag-bw) 30 cm or less thick that, throughout has *both*
    (a) has a moist chroma less than 6, *and*
    (b) is either apedal (massive or single-grain) and has weak or very weak moist, unconfined soil strength.

::: {style="text-align: right"}
**Immature Orthic Brown Soils**
:::

#### **BOW** {#sec-key-BOW .unnumbered}

Other soils with coarse rock fragments that in the majority are weathered to the extent that they may easily be broken by hammer or spade.

::: {style="text-align: right"}
**Weathered Orthic Brown Soils**
:::

#### **BOP** {#sec-key-BOP .unnumbered}

Other soils that have in some part of the B or BC horizon within 90 cm from the mineral soil surface have EITHER

1.  Moist matrix colour of hue of 2.5Y or yellower, OR
2.  Moist matrix colour of hue of 10YR and chroma 4 or less with *either*
    (a) no more than a slight reaction to the [reactive-aluminium test](Diagnostics.qmd#sec-diag-naf), *or*
    (b) a [cutanic horizon](Diagnostics.qmd#sec-diag-cuth), *or*
    (c) P-retention less than 30%.

::: {style="text-align: right"}
**Pallic Orthic Brown Soils**
:::

#### **BOA** {#sec-key-BOA .unnumbered}

Other soils that have pH less than 5.5 in some part of the B or BC horizon to 60 cm from the mineral soil surface.

::: {style="text-align: right"}
**Acidic Orthic Brown Soils**
:::

#### **BOC** {#sec-key-BOC .unnumbered}

Other soils that have in part of the B or BC horizon a [calcareous horizon](Diagnostics.qmd#sec-diag-calch) within 60 cm of the mineral soil surface.

::: {style="text-align: right"}
**Calcareous Orthic Brown Soils**
:::

#### **BOT** {#sec-key-BOT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Orthic Brown Soils**
:::

{{< pagebreak >}}
