# New Zealand Soil Classification {.unnumbered}

*4^th^ edition*

Landcare Research Science Series No. 1

*© New Zealand Institute for Bioeconomy Science Ltd 2026*

No part of this work covered by copyright may be reproduced or copied in any form or by any means (graphic, electronic or mechanical, including photocopying, recording, taping, information retrieval systems, or otherwise) without the written permission of the publisher.

A catalogue record for this book is available from the National Library of New Zealand:

> HEWITT, A.E. and NZSC Working Group\
> New Zealand soil classification / A.E. Hewitt and NZSC Working Group – 4th edition – Lincoln, N.Z.:\
> New Zealand Institute for Bioeconomy Science 2026.\
> (Landcare Research science series, ISSN 1172-269X; no.1)\
> ISBN 978-1-997319-05-4 (PDF)\
> \
> 1 Soils – New Zealand – Classification. I.\
> Manaaki Whenua – Landcare Research New Zealand Ltd. II. Title. III. Series.\
> \
> UDC 631.44 (931)

Published by New Zealand Institute for Bioeconomy Science, Manaaki Whenua – Landcare Research Group, 74 Gerald Street, Lincoln 7608, New Zealand

*First published as DSIR Land Resources Scientific Report No.19, 1992.\
Reprinted with corrections as Landcare Research Science Series No. 1, 1993.\
Reprinted with update and corrections as Landcare Research Science Series No. 1, 1998 (2^nd^ edition) and 2010 (3^rd^ edition).\
This is the 4th edition with further updates and corrections.*

The PDF version of this book can be downloaded from [https://soils.landcareresearch.co.nz/topics/soil-classification/nzsc/nzsc-4th-edition](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsoils.landcareresearch.co.nz%2Ftopics%2Fsoil-classification%2Fnzsc%2Fnzsc-4th-edition&data=05%7C02%7COBrienL%40landcareresearch.co.nz%7C4fbabae9a1e24140769e08df086fe91c%7C43050530b3c74cd2a11cb826b2604b5b%7C0%7C0%7C639238948900194155%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=eo8ta1g0sBeHNOtTRARK5JFk4AbTbkVpYJssO2XPl6E%3D&reserved=0 "Original URL: https://soils.landcareresearch.co.nz/topics/soil-classification/nzsc/nzsc-4th-edition. Click or tap if you trust this link.").

Please email [soilstandards\@landcareresearch.co.nz](mailto:soilstandards@landcareresearch.co.nz?subject=NZSSS%204th%20edition) if you have any questions or comments about this new edition.

{{< pagebreak >}}
