---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Melanic Soils {#sec-ord-E}

## Concept of the Order {#sec-con-E}

Melanic Soils are well structured soils with very dark A horizons. They commonly have high base saturation, combined with weakly alkaline or weakly acidic subsurface horizons, but more acidified and allophanic variants may exist under higher soil moisture regimes. Their parent materials are rich in calcium and/or magnesium.

## Correlation {#sec-cor-E}

The Melanic Soils include the rendzinas and rendzic intergrades to yellow-grey earths and yellow-brown earths. They also include the weakly weathered and drier brown-granular loams and clays of the *New Zealand Genetic Soil Classification*. Most correlate with Mollisols, Vertisols and Inceptisols of *Soil Taxonomy*.

## Occurrence {#sec-occ-E}

Melanic Soils are scattered throughout New Zealand in association with calcareous, mafic, and ultramafic rocks.

## Accessory Properties of the Order {#sec-acc-E}

1.  *Swelling clays.* Most soils have smectite, or minerals with interstratifications of smectite, in the clay mineral assemblage. Melanic Soils usually have a Smectitic, Illitic or Kandic mineralogy class.
2.  *High base saturations.* Except for acidified variants, base saturations are usually more than 50%, and KCl-extractable aluminium values are usually very low.
3.  *Stable structure.* Structural stability of topsoils is high with relatively large amounts of organic carbon intimately associated with clay minerals. The soils are likely to have relatively high resistance to structural damage under heavy cropping unless organic matter is reduced significantly. The porosity is stabilised by divalent ion/organic matter/ clay complexes.
4.  *High shrink/swell.* The soil materials are sticky and plastic. They are expected to have significant shrink/swell potential. This is reflected in strong polyhedral, blocky or prismatic pedality. P retention values are moderate to high.
5.  *Fertile.* Except for acidified variants, exchangeable calcium and magnesium values are high, particularly at the base of profile.
6.  *Parent materials.* The soils are derived from calcareous, mafic or ultramafic rock classes.
7.  *Deep rooting depth.* Except for shallow soils on rock or soils affected by high water-tables, potential rooting depths are relatively large.
8.  *Biologically active.* Carbon/nitrogen ratios are low (except in areas with very high precipitation).

## Summary of Melanic Soils Hierarchy {#sec-sum-E}

```{r}
#| label: tbl-E
#| tbl-cap: "Melanic Soils"
#| classes: '.plain .hover'

library(gt)

table_E_dat <- data.frame(
  'Code' = c('EV', rep('', 3),
             'EP', rep('', 2),
             'ER', rep('', 3),
             'EM', rep('', 4),
             'EO', rep('', 7)),
  'Group' = c('Vertic', rep('', 3),
              'Perch-gley', rep('', 2),
              'Rendzic', rep('', 3),
              'Mafic', rep('', 4),
              'Orthic', rep('', 7)),
  'Subgroup' = c('Mottled-calcareous', 'Mottled', 'Calcareous', 'Typic',
                 'Vertic', 'Argillic', 'Typic',
                 'Peaty', 'Mottled', 'Weathered', 'Typic',
                 'Magnesic', 'Mottled', 'Allophanic', 'Acidic', 'Typic',
                 'Mottled-calcareous', 'Argillic-calcareous', 'Pedal-calcareous',
                   'Calcareous', 'Mottled-argillic', 'Mottled', 'Argillic', 'Typic'),
  'Example_Series' = c('-', 'Waiareka', 'Te Aneraki', 'Waiareka',
                       'Awapuni', 'Okoia', '-',
                       'Chalky', '-', 'Te Matai', 'Oamaru',
                       'Dun', 'Awapuku', 'Stewart', 'Stewart', 'Rapaki',
                       'Waikakahi', 'Kauana', 'Waikakahi', 'Pikikiruna',
                         '-', '-', 'Kaihiku', 'Bishopdale')
) 

table_E <- gt(table_E_dat) |>
  tab_options(
    column_labels.font.weight = 'bold', 
    heading.title.font.weight = 'bold',
    table.align = 'center',
    table.width = '95%'
  ) |>
  cols_label(Example_Series = 'Example Series') |>
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(columns = 1)) |>
  cols_width(Code ~pct(10),  Group ~pct(20), Subgroup ~pct(35))

table_E
```

## Key to Groups of Melanic Soils {#sec-grp-E}

#### **EV** {#sec-key-EV .unnumbered}

Melanic Soils that have BOTH

1.  *Either*
    (a) cracks at least 4 mm wide in some part, either in the B horizon infilled with A horizon material, or extending to a depth of 30 cm or more from the mineral soil surface, *or*
    (b) coefficient of linear expandibility of 0.09 or more, pedality that is moderate or strong, and blocky or prismatic in the major part of the B horizon, AND
2.  No [redox segregations](Diagnostics.qmd#sec-diag-rsegs) within 30 cm of the mineral soil surface.

::: {style="text-align: right"}
[**VERTIC MELANIC SOILS**](#sec-EV)
:::

#### **EP** {#sec-key-EP .unnumbered}

Other soils that have BOTH

1.  A [peaty topsoil](Diagnostics.qmd#sec-diag-pts) or a [gley profile form](Diagnostics.qmd#sec-diag-gleypf), AND
2.  [Perch-gley features](Diagnostics.qmd#sec-diag-pgley).

::: {style="text-align: right"}
[**PERCH-GLEY MELANIC SOILS**](#sec-EP)
:::

#### **ER** {#sec-key-ER .unnumbered}

Other soils that have limestone or other calcareous parent material either in the form of a [lithic](Diagnostics.qmd#sec-diag-lithc) or [paralithic contact](Diagnostics.qmd#sec-diag-plith), or contain a high proportion of coarse rock fragments (70% or more by volume) in the form of rock rubble, with an upper boundary at 60 cm or less and which continues to more than 90 cm from the mineral soil surface.

::: {style="text-align: right"}
[**RENDZIC MELANIC SOILS**](#sec-ER)
:::

#### **EM** {#sec-key-EM .unnumbered}

Other soils that, in a subhorizon of the B or BC horizon at 60 cm from the mineral soil surface, or at the base of the B or BC if shallower, have at least ONE of the following:

1.  A matrix colour value 4 or less and chroma 3 or more, OR
2.  5% (by volume) or more coarse rock fragments that consist mainly of mafic or ultramafic rocks (but not tuffaceous greywacke), OR
3.  an exchangeable calcium/magnesium molar ratio of 0.2 or less and exchangeable magnesium of 1.5 cmol~c~/kg or more.

::: {style="text-align: right"}
[**MAFIC MELANIC SOILS**](#sec-EM)
:::

#### **EO** {#sec-key-EO .unnumbered}

Other soils.

::: {style="text-align: right"}
[**ORTHIC MELANIC SOILS**](#sec-EO)
:::

## Key to Subgroups of Melanic Soils {#sec-sub-E}

### **EV** - VERTIC MELANIC SOILS {#sec-EV .unnumbered}

Vertic Melanic Soils occur in clayey soil materials dominated by clay minerals with high capacity to shrink on drying and swell on rewetting.

#### **EVMC** {#sec-key-EVMC .unnumbered}

Vertic Melanic Soils that have BOTH

1.  [Redox segregations](Diagnostics.qmd#sec-diag-rsegs) within 60 cm of the mineral soil surface, *and*
2.  A [calcareous horizon](Diagnostics.qmd#sec-diag_calch) within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Mottled-calcareous Vertic Melanic Soils**
:::

#### **EVM** {#sec-key-EVM .unnumbered}

Other soils that have [redox segregations](Diagnostics.qmd#sec-diag-rsegs) within 60 cm of the mineral soil surface.

::: {style="text-align: right"}
*Mottled Vertic Melanic Soils*
:::

#### **EVC** {#sec-key-EVC .unnumbered}

Other soils with a [calcareous horizon](Diagnostics.qmd#sec-diag-calch) within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Calcareous Vertic Melanic Soils**
:::

#### **EVT** {#sec-key-EVT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Vertic Melanic Soils**
:::

### **EP** - PERCH-GLEY MELANIC SOILS {#sec-EP .unnumbered}

Perch-gley Melanic Soils occur in sites that are periodically saturated (unless artificially drained). Wetness and associated reducing conditions are indicated by [low-chroma colours](Diagnostics.qmd#sec-diag-lch) in horizons subjacent to the topsoil, and are caused by perching of water on a [slowly permeable layer](Diagnostics.qmd#sec-diag-slowp), although a groundwater-table may also be present.

#### **EPV** {#sec-key-EPV .unnumbered}

Perch-gley Melanic Soils that have EITHER

1.  Cracks at least 4 mm wide in some part, either in the B horizon infilled with A horizon material, or extending to a depth of 30 cm or more, from the mineral soil surface, OR
2.  Coefficient of linear expandability of 0.09 or more, with pedality that is moderate or strong, and blocky or prismatic in the major part of the B horizon.

::: {style="text-align: right"}
**Vertic Perch-gley Melanic Soils**
:::

#### **EPJ** {#sec-key-EPJ .unnumbered}

Other soils with an [argillic horizon](Diagnostics.qmd#sec-diag-argh).

::: {style="text-align: right"}
**Argillic Perch-gley Melanic Soils**
:::

#### **EPT** {#sec-key-EPT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Perch-gley Melanic Soils**
:::

### **ER** - RENDZIC MELANIC SOILS {#sec-ER .unnumbered}

Rendzic Melanic Soils occur in soils in which limestone or calcareous sedimentary rocks or rock debris occur at shallow depths.

#### **ERO** {#sec-key-ERO .unnumbered}

Rendzic Melanic Soils that have a [peaty topsoil](Diagnostics.qmd#sec-diag-pts).

::: {style="text-align: right"}
**Peaty Rendzic Melanic Soils**
:::

#### **ERM** {#sec-key-ERM .unnumbered}

Other soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Rendzic Melanic Soils**
:::

#### **ERW** {#sec-key-ERW .unnumbered}

Other soils that have a [weathered-B](Diagnostics.qmd#sec-diag-bw) or [cutanic horizon](Diagnostics.qmd#sec-diag-cuth) 10 cm or more thick.

::: {style="text-align: right"}
**Weathered Rendzic Melanic Soils**
:::

#### **ERT** {#sec-key-ERT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Rendzic Melanic Soils**
:::

### **EM** - MAFIC MELANIC SOILS {#sec-EM .unnumbered}

Mafic Melanic Soils occur in soil materials weathered from mafic rocks, ultramafic rocks or tuffs (but not tuffaceous greywacke). They have relatively high proportions of dark-coloured magnesium- and iron-rich silicate minerals.

#### **EMG** {#sec-key-EMG .unnumbered}

Mafic Melanic Soils that have, in some part of the B or BC horizon to 60 cm from the mineral soil surface, EITHER

1.  5% (by volume) or more coarse rock fragments that consist mainly of ultramafic rocks, OR
2.  Have an exchangeable calcium/magnesium molar ratio of 0.2 or less and exchangeable magnesium of 1.5 cmol~c~/kg or more.

::: {style="text-align: right"}
**Magnesic Mafic Melanic Soils**
:::

#### **EMM** {#sec-key-EMM .unnumbered}

Other soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Mafic Melanic Soils**
:::

#### **EML** {#sec-key-EML .unnumbered}

Other soils that have P-retention 85% or more, or a strong reaction to the [reactive-aluminium test](Diagnostics.qmd#sec-diag-naf), in some part of the B or BC horizon, within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Allophanic Mafic Melanic Soils**
:::

#### **EMA** {#sec-key-EMA .unnumbered}

Other soils that have pH less than 5.5 in some part of the B or BC horizon, within 60 cm of the mineral soil surface.

::: {style="text-align: right"}
**Acidic Mafic Melanic Soils**
:::

#### **EMT** {#sec-key-EMT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Mafic Melanic Soils**
:::

### **EO** - ORTHIC MELANIC SOILS {#sec-EO .unnumbered}

Orthic Melanic Soils occur in soil materials containing calcium carbonate or that have high calcium contents.

#### **EOMC** {#sec-key-EOMC .unnumbered}

Orthic Melanic Soils that have both a [calcareous horizon](Diagnostics.qmd#sec-diag-calch) with an upper surface at 90 cm or less from the mineral soil surface, and a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled-calcareous Orthic Melanic Soils**
:::

#### **EOJC** {#sec-key-EOJC .unnumbered}

Other soils that have an [argillic horizon](Diagnostics.qmd#sec-diag-argh) and a [calcareous horizon](Diagnostics.qmd#sec-diag-calch) with an upper surface at 90 cm or less from the mineral soil surface.

::: {style="text-align: right"}
**Argillic-calcareous Orthic Melanic Soils**
:::

#### **EODC** {#sec-key-EODC .unnumbered}

Other soils that have a moderately or strongly pedal [weathered-B horizon](Diagnostics.qmd#sec-diag-bw) 15 cm or more thick occurring immediately beneath the A horizon, and a [calcareous horizon](Diagnostics.qmd#sec-diag-calch) with an upper surface at 90 cm or less from the mineral soil surface.

::: {style="text-align: right"}
**Pedal-calcareous Orthic Melanic Soils**
:::

#### **EOC** {#sec-key-EOC .unnumbered}

Other soils that have a [calcareous horizon](Diagnostics.qmd#sec-diag-calch) with an upper surface at 90 cm or less from the mineral soil surface.

::: {style="text-align: right"}
**Calcareous Orthic Melanic Soils**
:::

#### **EOMJ** {#sec-key-EOMJ .unnumbered}

Other soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf), and an [argillic horizon](Diagnostics.qmd#sec-diag-argh).

::: {style="text-align: right"}
**Mottled-argillic Orthic Melanic Soils**
:::

#### **EOM** {#sec-key-EOM .unnumbered}

Other soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Orthic Melanic Soils**
:::

#### **EOJ** {#sec-key-EOJ .unnumbered}

Other soils that have an [argillic horizon](Diagnostics.qmd#sec-diag-argh).

::: {style="text-align: right"}
**Argillic Orthic Melanic Soils**
:::

#### **EOT** {#sec-key-EOT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Orthic Melanic Soils**
:::

{{< pagebreak >}}
