# Pallic Soils {#sec-ord-P}

## Concept of the Order {#sec-con-P}

Pallic Soils are soils with moderate to high base status and low contents of secondary iron oxides. They have pale colours, high slaking potential and high density in subsurface horizons. Pallic Soils have water deficits in summer, and soil water surpluses in winter or spring.

## Correlation {#sec-cor-P}

The order comprises most yellow-grey earths, associated steepland soils, intergrades between yellow-grey earths and yellow-brown earths, and intergrades between yellow-grey earths and brown-grey earths of the *New Zealand Genetic Soil Classification*. Most Pallic Soils are correlated with Alfisols and Inceptisols in *Soil Taxonomy*, particularly those under ustic (predominant) or udic moisture regimes, with aquic conditions, or ochric epipedons.

## Occurrence {#sec-occ-P}

Pallic Soils occur predominantly in the seasonally dry eastern part of North and South Islands and in the Manawatū.

## Accessory Properties of the Order {#sec-acc-P}

1.  *Low concentrations of secondary oxides.* P retention is less than 30% in topsoils and in subsoils. Extractable iron and aluminium values are low or moderate, with a significant proportion of secondary iron oxides occurring in [redox segregations](Diagnostics.qmd#sec-diag-rsegs).
2.  *High base status.* Base saturation values in subsoils are high (more than 50%) except in perch-gleyed soils, where values may be lower in horizons overlying [fragipans](Diagnostics.qmd#sec-diag-fpan).
3.  *Felsic parent materials.* Parent materials are predominantly loess or sediments derived from quartzo-feldspathic rocks (schist or greywacke).
4.  *Mica/illite clay minerals.* Pallic Soils usually belong either to the Illitic or Vermilculitic, or to a Clay-mineralic mineralogy class.
5.  *Slow permeability.* Subsurface horizons have restricted permeability, particularly in soils with fragipans or duripans in which the permeability is very slow.
6.  *Perched water-tables.* Soils that are poorly or moderately well drained have water-tables perched on [slowly permeable layers](Diagnostics.qmd#sec-diag-slowp).
7.  *Limited rooting depth.* Potential rooting depth in most soils is limited by a subsurface horizon of high bulk density at shallow depths or by brittle silty cappings on coarse rock fragments.
8.  *Strongly worm-mixed.* Topsoils generally have a significant proportion of worm casts and a distinct worm-mixed horizon occurs in the transition from A to B horizons. Topsoil worm activity is greatly reduced during summer periods of soil moisture deficit.
9.  *High slaking and dispersion potential.* Soil material, particularly in B horizons, is strongly dispersive and will readily slake. Topsoil structures may break down under prolonged impact by heavy machinery or by continuous tillage.
10. *Droughty summers, moist winters.* Average annual precipitation ranges from about 500 to 1000 mm per year. A spring surplus of soil water is common but the annual surplus is less than about 200 mm. The average annual deficit is approximately 90–200 mm/year.
11. *Phosphorus status.* A high proportion of the inorganic phosphorus is non-occluded and a relatively high proportion of total phosphorus is in an organic form.
12. *Sulfur status.* Levels of extractable sulfate are low.

## Summary of Pallic Soils Hierarchy {#sec-sum-P}

```{r}
#| label: tbl-P
#| tbl-cap: "Pallic Soils"
#| classes: '.plain .hover'

library(gt)

table_P_dat <- data.frame(
  'Code' = c('PP', rep('', 6),
             'PU', rep('', 3),
             'PX', rep('', 8),
             'PL', rep('', 2),
             'PJ', rep('', 8),
             'PI', rep('', 4)),
  'Group' = c('Perch-gley', rep('', 6),
              'Duric', rep('', 3),
              'Fragic', rep('', 8),
              'Laminar', rep('', 2),
              'Argillic', rep('', 8),
              'Immature', rep('', 4)),
  'Subgroup' = c(
    # PP
    'Duric', 'Argillic-fragic', 'Fragic', 'Weathered-argillic', 'Argillic', 'Cemented', 'Typic',
    # PU
    'Mottled', 'Argillic-sodic', 'Argillic', 'Typic',
    # PX
    'Argillic-sodic', 'Mottled-argillic', 'Argillic-calcareous', 'Argillic', 'Mottled-calcareous', 'Mottled', 'Calcareous-sodic',
                   'Calcareous', 'Typic', 
    # PL
    'Mottled', 'Calcareous', 'Typic',
    # PJ 
    'Mottled-ultic', 'Mottled-weathered', 'Mottled', 'Aged',  'Ultic', 'Sodic', 'Weathered', 'Calcareous', 'Typic',
    # PI
    'Mottled-pedal', 'Mottled', 'Calcareous', 'Pedal', 'Typic'),
  'Example_Series' = c('Poporangi', 'Tokomaru', 'Otokia', 'Nalder', 'Marton', 'Caroline', 'Salix',
                       'Matapiro', '-', 'Matapiro', '-',
                       'Wither', '-', 'Grampians', 'Seaview', 'Cluden', 'Timaru', 'Grampians', 'Takahe', 'Tima',
                       'Pukeuri', '-', 'Otama',
                       'Rosedale', 'Okuku', 'Halcombe', 'Naseby', 'Rosedale', '-', '-', '-', 'Abbotsford',
                       '-', 'Wakanui', '-', 'Kiwi', 'Templeton')
) 

table_P <- gt(table_P_dat) |>
  tab_options(
    column_labels.font.weight = 'bold', 
    heading.title.font.weight = 'bold',
    table.align = 'center',
    table.width = '95%'
  ) |>
  cols_label(Example_Series = 'Example Series') |>
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(columns = 1)) |>
  cols_width(Code ~pct(10),  Group ~pct(20), Subgroup ~pct(35))

table_P
```

## Key to Groups of Pallic Soils {#sec-grp-p}

#### **PP** {#sec-key-PP .unnumbered}

Pallic Soils that have both a [gley profile form](Diagnostics.qmd#sec-diag-gleypf) and [perch-gley features](Diagnostics.qmd#sec-diag-pgley).

::: {style="text-align: right"}
[**PERCH-GLEY PALLIC SOILS**](#sec-PP)
:::

#### **PU** {#sec-key-PU .unnumbered}

Other soils that have a [duripan](Diagnostics.qmd#sec-diag-dpan).

::: {style="text-align: right"}
[**DURIC PALLIC SOILS**](#sec-PU)
:::

#### **PX** {#sec-key-PX .unnumbered}

Other soils that have a [fragipan](Diagnostics.qmd#sec-diag-fpan).

::: {style="text-align: right"}
[**FRAGIC PALLIC SOILS**](#sec-PX)
:::

#### **PL** {#sec-key-PL .unnumbered}

Other soils that have a [brittle-B horizon](Diagnostics.qmd#sec-diag-britb) and an [argillic horizon](Diagnostics.qmd#sec-diag-argh) that is predominantly in the form of lamellae.

::: {style="text-align: right"}
[**LAMINAR PALLIC SOILS**](#sec-PL)
:::

#### **PJ** {#sec-key-PJ .unnumbered}

Other soils that have an [argillic horizon](Diagnostics.qmd#sec-diag-argh), or a [cutanic horizon](Diagnostics.qmd#sec-diag-cuth) with [sodic features](Diagnostics.qmd#sec-diag-sod) within it or immediately beneath it.

::: {style="text-align: right"}
[**ARGILLIC PALLIC SOILS**](#sec-PJ)
:::

#### **PI** {#sec-key-PI .unnumbered}

Other soils.

::: {style="text-align: right"}
[**IMMATURE PALLIC SOILS**](#sec-PI)
:::

## Key to Subgroups of Pallic Soils {#sec-sub-P}

### **PP** - PERCH-GLEY PALLIC SOILS {#sec-PP .unnumbered}

Perch-gley Pallic soils occur in sites that are periodically saturated (if undrained) in winter and spring, but dry out in summer. The wetness and associated reducing conditions are indicated by [low-chroma colours](Diagnostics.qmd#sec-diag-lch) on ped surfaces in horizons directly beneath the topsoil. Wetness is caused by perching of water on a [slowly permeable layer](Diagnostics.qmd#sec-siag-slowp) (e.g., [fragipan](Diagnostics.qmd#sec-diag-fpan), [argillic horizon](Diagnostics.qmd#sec-diag-argh), [duripan](Diagnostics.qmd#sec-diag-dpan)). The [reductimorphic horizons](Diagnostics.qmd#sec-diag-redmh) are commonly acidic (pH less than 5.5).

#### **PPU** {#sec-key-PPU .unnumbered}

Perch-gley Pallic Soils that have a [duripan](Diagnostics.qmd#sec-diag-dpan).

::: {style="text-align: right"}
**Duric Perch-gley Pallic Soils**
:::

#### **PPJX** {#sec-key-PPJX .unnumbered}

Other soils that have both an [argillic horizon](Diagnostics.qmd#sec-diag-argh) and a [fragipan](Diagnostics.qmd#sec-diag-fpan).

::: {style="text-align: right"}
**Argillic-fragic Perch-gley Pallic Soils**
:::

#### **PPX** {#sec-key-PPX .unnumbered}

Other soils that have a [fragipan](Diagnostics.qmd#sec-diag-fpan).

::: {style="text-align: right"}
**Fragic Perch-gley Pallic Soils**
:::

#### **PPWJ** {#sec-key-PPWJ .unnumbered}

Other soils in which the majority of coarse rock fragments are weathered enough to be easily be broken with hammer or spade, and that contain an [argillic horizon](Diagnostics.qmd#sec-diag-argh).

::: {style="text-align: right"}
**Weathered-argillic Perch-gley Pallic Soils**
:::

#### **PPJ** {#sec-key-PPJ .unnumbered}

Other soils that have an [argillic horizon](Diagnostics.qmd#sec-diag-argh).

::: {style="text-align: right"}
**Argillic Perch-gley Pallic Soils**
:::

#### **PPC** {#sec-key-PPC .unnumbered}

Other soils that have a horizon that is cemented to the degree that it is at least weakly indurated, within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Cemented Perch-gley Pallic Soils**
:::

#### **PPT** {#sec-key-PPT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Perch-gley Pallic Soils**
:::

### **PU** - DURIC PALLIC SOILS {#sec-PU .unnumbered}

Duric Pallic Soils occur in areas with pronounced soil moisture deficits and often have some proportion of tephra in the soil parent material, or high exchangeable sodium. The total silica contents are not exceptional, but sufficient silica has been mobilised to form a pan that impedes roots and water.

#### **PUM** {#sec-key-PUM .unnumbered}

Duric Pallic Soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Duric Pallic Soils**
:::

#### **PUJN** {#sec-key-PUJN .unnumbered}

Other soils that have an [argillic horizon](Diagnostics.qmd#sec-diag-argh), or a [cutanic horizon](Diagnostics.qmd#sec-diag-cuth) that within or immediately beneath has [sodic features](Diagnostics.qmd#sec-diag-sod).

::: {style="text-align: right"}
**Argillic-sodic Duric Pallic Soils**
:::

#### **PUJ** {#sec-key-PUJ .unnumbered}

Other soils that have an [argillic horizon](Diagnostics.qmd#sec-diag-argh).

::: {style="text-align: right"}
**Argillic Duric Pallic Soils**
:::

#### **PUT** {#sec-key-PUT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Duric Pallic Soils**
:::

### **PX** - FRAGIC PALLIC SOILS {#sec-PX .unnumbered}

Fragic Pallic Soils occur in soil materials that are predominantly silty. A [fragipan](Diagnostics.qmd#sec-diag-fpan) which severely restricts the movement of water and penetration of roots occurs below the base of the B horizon.

#### **PXJN** {#sec-key-PXJN .unnumbered}

Fragic Pallic Soils that have BOTH

1.  An [argillic](Diagnostics.qmd#sec-diag-argh) or [cutanic horizon](Diagnostics.qmd#sec-diag-cuth) overlying the [fragipan](Diagnostics.qmd#sec-diag-fpan), AND
2.  [Sodic features](Diagnostics.qmd#sec-diag-sod) within or immediately above the [fragipan](Diagnostics.qmd#sec-diag-fpan).

::: {style="text-align: right"}
**Argillic-sodic Fragic Pallic Soils**
:::

#### **PXMJ** {#sec-key-PXMJ .unnumbered}

Other soils that have BOTH

1.  An [argillic horizon](Diagnostics.qmd#sec-diag-argh) overlying the [fragipan](Diagnostics.qmd#sec-diag-fpan), AND
2.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Argillic-mottled Fragic Pallic Soils**
:::

#### **PXJC** {#sec-key-PXJC .unnumbered}

Other soils that have BOTH

1.  An [argillic horizon](Diagnostics.qmd#sec-diag-argh), AND
2.  A [calcareous horizon](Diagnostics.qmd#sec-diag-calch).

::: {style="text-align: right"}
**Argillic-calcareous Fragic Pallic Soils**
:::

#### **PXJ** {#sec-key-PXJ .unnumbered}

Other soils with an [argillic horizon](Diagnostics.qmd#sec-diag-argh) overlying the [fragipan](Diagnostics.qmd#sec-diag-fpan).

::: {style="text-align: right"}
**Argillic Fragic Pallic Soils**
:::

#### **PXMC** {#sec-key-PXMC .unnumbered}

Other soils that have BOTH

1.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf), AND
2.  A [calcareous horizon](Diagnostics.qmd#sec-diag-calch) immediately beneath the [fragipan](Diagnostics.qmd#sec-diag-fpan) or calcium carbonate occurs within prism interiors of the [fragipan](Diagnostics.qmd#sec-diag-fpan).

::: {style="text-align: right"}
**Mottled-calcareous Fragic Pallic Soils**
:::

#### **PXM** {#sec-key-PXM .unnumbered}

Other soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Fragic Pallic Soils**
:::

#### **PXCN** {#sec-key-PXCN .unnumbered}

Other soils that have BOTH

1.  A [calcareous horizon](Diagnostics.qmd#sec-diag-calch) immediately beneath the [fragipan](Diagnostics.qmd#sec-diag-fpan) or calcium carbonate occurs within prism interiors of the [fragipan](Diagnostics.qmd#sec-diag-fpan), AND
2.  [Sodic features](Diagnostics.qmd#sec-diag-sod) within or immediately beneath the [fragipan](Diagnostics.qmd#sec-diag-fpan).

::: {style="text-align: right"}
**Calcareous-sodic Fragic Pallic Soils**
:::

#### **PXC** {#sec-key-PXC .unnumbered}

Other soils that have a [calcareous horizon](Diagnostics.qmd#sec-diag-calch) immediately beneath the [fragipan](Diagnostics.qmd#sec-diag-fpan) or calcium carbonate occurs within prism interiors of the [fragipan](Diagnostics.qmd#sec-diag-fpan).

::: {style="text-align: right"}
**Calcareous Fragic Pallic Soils**
:::

#### **PXT** {#sec-key-PXT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Fragic Pallic Soils**
:::

### **PL** - LAMINAR PALLIC SOILS {#sec-PL .unnumbered}

Laminar Pallic Soils occur predominantly in fine sandy or silty loess or alluvium. Although rooting is impeded in the subsurface horizons it is not restricted to the degree that it is in a [fragipan](Diagnostics.qmd#sec-diag-fpan). The soils are generally slowly permeable.

#### **PLM** {#sec-key-PLM .unnumbered}

Laminar Pallic Soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Laminar Pallic Soils**
:::

#### **PLC** {#sec-key-PLC .unnumbered}

Other soils that have a [calcareous horizon](Diagnostics.qmd#sec-diag-calch).

::: {style="text-align: right"}
**Calcareous Laminar Pallic Soils**
:::

#### **PLT** {#sec-key-PLT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Laminar Pallic Soils**
:::

### **PJ** - ARGILLIC PALLIC SOILS {#sec-PJ .unnumbered}

Argillic Pallic Soils have no [fragipan](Diagnostics.qmd#sec-diag-fpan) or [duric horizon](Diagnostics.qmd#sec-diag-dpan) but have a clay-enriched B horizon in which clay coatings occur predominantly on polyhedral, blocky or prismatic ped surfaces, on coarse rock fragment surfaces, or within tubular pores.

#### **PJMU** {#sec-key-PJMU .unnumbered}

Argillic Pallic Soils that have BOTH

1.  An [eluvial horizon](Diagnostics.qmd#sec-diag-eluv) and pH less than 5.5 in some part of the [argillic horizon](Diagnostics.qmd#sec-diag-argh), AND
2.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled-ultic Argillic Pallic Soils**
:::

#### **PJMW** {#sec-key-PJMW .unnumbered}

Other soils that have BOTH

1.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf), AND
2.  Coarse rock fragments, the majority of which are weathered to the extent that clasts can be easily broken by hammer or spade.

::: {style="text-align: right"}
**Mottled-weathered Argillic Pallic Soils**
:::

#### **PJM** {#sec-key-PJM .unnumbered}

Other soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Argillic Pallic Soils**
:::

#### **PJA** {#sec-key-PJA .unnumbered}

Other soils that have hue 7.5YR or redder or hue 10YR and chroma 6 or more in some part of the [argillic horizon](Diagnostics.qmd#sec-diag-argh).

::: {style="text-align: right"}
**Aged Argillic Pallic Soils**
:::

#### **PJU** {#sec-key-PJU .unnumbered}

Other soils that have an [eluvial horizon](Diagnostics.qmd#sec-diag-eluv) and pH less than 5.5 in some part of the [argillic horizon](Diagnostics.qmd#sec-diag-argh).

::: {style="text-align: right"}
**Ultic Argillic Pallic Soils**
:::

#### **PJN** {#sec-key-PJN .unnumbered}

Other soils that have [sodic features](Diagnostics.qmd#sec-diag-sod) within or immediately beneath the [argillic horizon](Diagnostics.qmd#sec-diag-argh).

::: {style="text-align: right"}
**Sodic Argillic Pallic Soils**
:::

#### **PJW** {#sec-key-PJW .unnumbered}

Other soils that have  coarse rock fragments, the majority of which are weathered to the extent that clasts can be easily broken by hammer or spade.

::: {style="text-align: right"}
**Weathered Argillic Pallic Soils**
:::

#### **PJC** {#sec-key-PJC .unnumbered}

Other soils that have a [calcareous horizon](Diagnostics.qmd#sec-diag-calch) with an upper surface occurring within 90 cm of the mineral soil surface, or occurring within or immediately below the [argillic horizon](Diagnostics.qmd#sec-diag-argh).

::: {style="text-align: right"}
**Calcareous Argillic Pallic Soils**
:::

#### **PJT** {#sec-key-PJT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Argillic Pallic Soils**
:::

### **PI** - IMMATURE PALLIC SOILS {#sec-PI .unnumbered}

Immature Pallic Soils are insufficiently developed to have [fragipans](Diagnostics.qmd#sec-diag-fpan), [duripans](Diagnostics.qmd#sec-diag-dpan) or [argillic horizons](Diagnostics.qmd#sec-diag-argh). They have either a [brittle-B horizon](Diagnostics.qmd#sec-diag-britb), an [eluvial horizon](Diagnostics.qmd#sec-diag-eluvh), a [cutanic horizon](Diagnostics.qmd#sec-diag-cuth), or slightly firm or stronger blocky, polyhedral or prismatic peds.

#### **PIMD** {#sec-key-PIMD .unnumbered}

Immature Pallic Soils that have BOTH

1.  A [mottled profile form](Diagnostics.qmd#sec-diag-mottpf), AND
2.  Are moderately or strongly pedal, with peds 100 mm or less in horizontal diameter, throughout the major part of the B horizon to 60 cm from the mineral soil surface, or to the base of the B horizon if shallower.

::: {style="text-align: right"}
**Mottled-pedal Immature Pallic Soils**
:::

#### **PIM** {#sec-key-PIM .unnumbered}

Other soils that have a [mottled profile form](Diagnostics.qmd#sec-diag-mottpf).

::: {style="text-align: right"}
**Mottled Immature Pallic Soils**
:::

#### **PIC** {#sec-key-PIC .unnumbered}

Other soils that have a [calcareous horizon](Diagnostics.qmd#sec-diag-calch) with an upper surface within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Calcareous Immature Pallic Soils**
:::

#### **PID** {#sec-key-PID .unnumbered}

Other soils that are moderately or strongly pedal, with peds 100 mm or less in horizontal diameter, throughout the major part of the B horizon to 60 cm from the mineral soil surface, or to the base of the B horizon if shallower.

::: {style="text-align: right"}
**Pedal Immature Pallic Soils**
:::

#### **PIT** {#sec-key-PIT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Immature Pallic Soils**
:::

{{< pagebreak >}}
