---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Podzol Soils {#sec-ord-Z}

## Concept of the Order {#sec-con-Z}

Podzols are acidic soils with low base saturation. Podzol Soils have a horizon of aluminium accumulation occurring as complexes with organic matter and/or as nanocrystalline minerals including allophane (with some imogolite) that result from the translocation of silicon as well as aluminium in solution as proto-imogolite. Iron (typically as ferrihydrite) may or may not accumulate with aluminium and silicon. This [podzolic-B horizon](Diagnostics.qmd#sec-diag-podzb) is usually associated with an overlying [eluvial horizon](#sec-diag-eluvh) indicating translocation. The [podzolic-B horizon](Diagnostics.qmd#sec-diag-podzb) can develop into a [placic horizon](Diagnostics.qmd#sec-diag-plac) or [ortstein-pan](Diagnostics.qmd#sec-diag-opan) if cementation occurs. The [eluvial horizon](#sec-diag-eluvh) may be missing due to erosion, ploughing, or bioturbation, or it may be masked by organic matter.

## Correlation {#sec-cor-Z}

Podzol Soils correspond to the podzols and some podzolised yellow-brown earths of the *New Zealand Genetic Soil Classification*. They mostly correspond with the Spodosols of *Soil Taxonomy*.

## Occurrence {#sec-occ-Z}

Podzol Soils occur in areas of high precipitation and are usually associated with forest species which produce an acidic litter. They are most common in Northland, the West Coast of the South Island, Stewart Island and throughout New Zealand at higher elevations.

## Accessory Properties of the Order {#sec-acc-Z}

1.  *Secondary oxides strongly differentiated between horizons.* In A and E horizons, sand and silt grains are uncoated. In B horizons they are coated, and in some soils cemented, by nanocrystalline minerals and/or organic matter.
2.  *Low base saturation.* Base saturations are very low, and the soils are extremely acidic, in A and E horizons. KCl-extractable-aluminium levels are high, and aluminium in soil solution may be toxic to some plants.
3.  *Parent materials.* The soils occur mainly in materials from felsic rocks such as granite, greywacke, schist or rhyolite, and derivatives including loess and tephra deposits.
4.  *Mineralogically differentiated.* Mica-smectite or smectite often occur in A and E horizons, and hydroxy-coated or interlayered minerals or allophane often occur in the B horizon. In some Northland soils, silica is dominant in B horizons. Podzols cover a wide range of mineralogy classes.
5.  *Limited rooting depth.* The rooting depth is limited for many introduced plants by low pH or aluminium toxicity, or by pans which often impede drainage.
6.  *Low biological activity.* Low levels of faunal activity occur with a low rate of mineralisation. Carbon/nitrogen ratios are very high. The accumulation of weakly decomposed humus and minimal incorporation of humus into the upper mineral soil results in a mor-like humus form.
7.  *Mor-forming vegetation.* The soils have been associated with vegetation producing an acid litter of low nutrient content (mainly *Agathis australis*, *Nothofagaceae*, *Podocarpaceae*).
8.  *Infertile.* The soils have very low natural fertility and require a high level of fertiliser addition under agricultural land use.
9.  *Wet climate.* The soils occur mainly in areas with an average annual precipitation of 1400 mm or more and, unless sandy, are likely to have a soil water surplus for a considerable part of the year.

## Summary of Podzol Soils Hierarchy {#sec-sum-Z}

```{r}
#| label: tbl-Z
#| tbl-cap: "Podzol Soils"
#| classes: '.plain .hover'

library(gt)

table_Z_dat <- data.frame(
  'Code' = c('ZD', rep('', 5),
             'ZP', rep('', 9),
             'ZG', '',
             'ZX', rep('', 6),
             'ZO', rep('', 2)),
  'Group' = c('Densipan', rep('', 5),
              'Perch-gley', rep('', 9),
              'Groundwater-gley', '',
              'Pan', rep('', 6),
              'Orthic', rep('', 2)),
  'Subgroup' = c('Humus-pan', 'Argillic-humose', 'Ultic-humose', 'Humose', 'Ortstein', 'Typic',
                 'Fluid', 'Peaty-silt-mantled', 'Silt-mantled', 'Humus-pan', 
                   'Humose-ortstein', 'Humose-placic', 'Humose', 'Ortstein',
                   'Placic', 'Typic',
                 'Humose', 'Typic',
                 'Humus-pan', 'Argillic-humose', 'Humose', 'Fragic', 'Ortstein', 'Placic',
                   'Firm',
                 'Argillic-humose', 'Humose', 'Typic'),
  'Example_Series' = c('Te Kopuru', 'Wharekohe', 'Wharekohe', 'Te Kopuru', 'Onahau', 'Parahaki',
                       'Hukarere', 'Okarito', 'Okarito', 'Addison', 
                         'Rutherglen', 'Rakiura', 'Maimai', 'Charleston', 
                         'Maungatua', 'Rowallan',
                       '-', '-',
                       'Kairua', '-', 'Tautuku', 'Nevis', 'Te Kopuru', 'Pukepahi', '-',
                       'Hūkerenui',  'Borland', 'Shewell')
) 

table_Z <- gt(table_Z_dat) |>
  tab_options(
    column_labels.font.weight = 'bold', 
    heading.title.font.weight = 'bold',
    table.align = 'center',
    table.width = '95%'
  ) |>
  cols_label(Example_Series = 'Example Series') |>
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(columns = 1)) |>
  cols_width(Code ~pct(10),  Group ~pct(20), Subgroup ~pct(35))

table_Z
```

## Key to Groups of Podzol Soils {#sec-grp-Z}

#### **ZD** {#sec-key-ZD .unnumbered}

Podzol Soils that have a [densipan](Diagnostics.qmd#sec-diag-dens) (Ed horizon).

::: {style="text-align: right"}
[**DENSIPAN PODZOL SOILS**](#sec-ZD)
:::

#### **ZP** {#sec-key-ZP .unnumbered}

Other Podzol Soils that have BOTH

1.  An [eluvial horizon](Diagnostics.qmd#sec-diag-eluv) with either the [low-chroma colours](Diagnostics.qmd#sec-diag-lch) of a [reductimorphic horizon](Diagnostics.qmd#sec-diag-redmh), a [peaty topsoil](Diagnostics.qmd#sec-diag-pts), or a [placic horizon](Diagnostics.qmd#sec-diag-plac) with [redox-segregations](Diagnostics.qmd#sec-diag-rsegs) in the [eluvial horizon](Diagnostics.qmd#sec-diag-eluv), AND
2.  A [slowly permeable layer](Diagnostics.qmd#sec-diag-slowp) or [perch-gley features](Diagnostics.qmd#sec-diag-pgley).

::: {style="text-align: right"}
[**PERCH-GLEY PODZOL SOILS**](#sec-ZP)
:::

#### **ZG** {#sec-key-ZG .unnumbered}

Other Podzol Soils that have BOTH

1.  Either an [Eluvial horizon](Diagnostics.qmd#sec-diag-eluv) with the [low-chroma colours](Diagnostics.qmd#sec-diag-lch) of a [reductimorphic horizon](Diagnostics.qmd#sec-diag-redmh) or a [peaty topsoil](Diagnostics.qmd#sec-diag-pts), AND
2.  A BC or C horizon that has the [low-chroma colours](Diagnostics.qmd#sec-diag-lch) of a [reductimorphic horizon](Diagnostics.qmd#sec-diag-redmh), that *either*
    (a) extends to more than 90 cm from the mineral soil surface, *or*
    (b) has [redox segregations](Diagnostics.qmd#sec-diag-rsegs) that occur mainly as coatings on voids and/or skeletans.

::: {style="text-align: right"}
[**GROUNDWATER-GLEY PODZOL SOILS**](#sec-ZG)
:::

#### **ZX** {#sec-key-ZX .unnumbered}

Other Podzol Soils that have a subhorizon in the B horizon that is BOTH

1.  Apedal massive, AND
2.  Has firm or greater moist, unconfined soil strength or has moist or wet penetration resistance of 3100 kPa or more.

::: {style="text-align: right"}
[**PAN PODZOL SOILS**](#sec-ZX)
:::

#### **ZO** {#sec-key-ZO .unnumbered}

Other Podzol Soils.

::: {style="text-align: right"}
[**ORTHIC PODZOL SOILS**](#sec-ZO)
:::

## Key to Subgroups of Podzol Soils {#sec-sub-Z}

### **ZD** - DENSIPAN PODZOL SOILS {#sec-ZD .unnumbered}

Densipan Podzol Soils have a high density but uncemented pan within the [eluvial horizon](Diagnostics.qmd#sec-diag-eluv) at shallow depths which severely limits root penetration and water movement.

#### **ZDU** {#sec-key-ZDU .unnumbered}

Densipan Podzol Soils that have a [humus-pan](Diagnostics.qmd#sec-diag-hpan).

::: {style="text-align: right"}
**Humus-pan Densipan Podzol Soils**
:::

#### **ZDJH** {#sec-key-ZDJH .unnumbered}

Other soils that have an [argillic horizon](Diagnostics.qmd#sec-diag-argh) beneath the Bh horizon.

::: {style="text-align: right"}
**Argillic-humose Densipan Podzol Soils**
:::

#### **ZDYH** {#sec-key-ZDYH .unnumbered}

Other soils that have a Bh horizon more than 5 cm thick that occurs within the top of a clayey prismatic B horizon.

::: {style="text-align: right"}
**Ultic-humose Densipan Podzol Soils**
:::

#### **ZDH** {#sec-key-ZDH .unnumbered}

Other soils that have a Bh horizon 5 cm or more thick.

::: {style="text-align: right"}
**Humose Densipan Podzol Soils**
:::

#### **ZDQ** {#sec-key-ZDQ .unnumbered}

Other soils that have an [ortstein-pan](Diagnostics.qmd#sec-diag-opan).

::: {style="text-align: right"}
**Ortstein Densipan Podzol Soils**
:::

#### **ZDT** {#sec-key-ZDT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Densipan Podzol Soils**
:::

### **ZP** - PERCH-GLEY PODZOL SOILS {#sec-ZP .unnumbered}

Perch-gley Podzol Soils occur in periodically, or predominantly, saturated sites (unless artificially drained) in which wetness is indicated by [low-chroma colours](Diagnostics.qmd#sec-diag-lch) along with brownish or reddish mottles or [peaty topsoils](Diagnostics.qmd#sec-diag-pts). The wetness is caused by the perching of water on a [slowly permeable layer](Diagnostics.qmd#sec-diag-slowp), although a groundwater-table may also be present.

#### **ZPF** {#sec-key-ZDF .unnumbered}

Perch-gley Podzol Soils that have a moderately fluid or very fluid fluidity class in some part above the [podzolic-B horizon](Diagnostics.qmd#sec-diag-podzb).

::: {style="text-align: right"}
**Fluid Perch-gley Podzol Soils**
:::

#### **ZPOZ** {#sec-key-ZPOZ .unnumbered}

Other soils that have BOTH

1.  an [eluvial horizon](Diagnostics.qmd#sec-diag-eluv) that has *all* of the following
    (a) a slightly firm or greater moist soil strength, *and*
    (b) an apedal-massive or very coarse to extremely coarse prismatic structure, *and*
    (c) is part of a silty layer that has a thickness of at least 15 cm, AND
2.  A [peaty topsoil](Diagnostics.qmd#sec-diag-pts).

::: {style="text-align: right"}
**Peaty-silt-mantled Perch-gley Podzol Soils**
:::

#### **ZPZ** {#sec-key-ZPZ .unnumbered}

Other soils that have an [eluvial horizon](Diagnostics.qmd#sec-diag-eluv) that has slightly firm or greater moist, unconfined soil strength, is apedal massive, or prismatic structure ranging from 60–200 mm in size, and occurs within a layer that is silty and at least 15 cm thick.

::: {style="text-align: right"}
**Silt-mantled Perch-gley Podzol Soils**
:::

#### **ZPU** {#sec-key-ZPU .unnumbered}

Other soils that have a [humus-pan](Diagnostics.qmd#sec-diag-hpan).

::: {style="text-align: right"}
**Humus-pan Perch-gley Podzol Soils**
:::

#### **ZPHQ** {#sec-key-ZPHQ .unnumbered}

Other soils that have a Bh horizon thicker than 5 cm, and an [ortstein-pan](Diagnostics.qmd#sec-diag-opan).

::: {style="text-align: right"}
**Humose-ortstein Perch-gley Podzol Soils**
:::

#### **ZPHP** {#sec-key-ZPHP .unnumbered}

Other soils that have a Bh horizon thicker than 5 cm, and a [placic horizon](Diagnostics.qmd#sec-diag_plac).

::: {style="text-align: right"}
**Humose-placic Perch-gley Podzol Soils**
:::

#### **ZPH** {#sec-key-ZPH .unnumbered}

Other soils that have a Bh horizon thicker than 5 cm.

::: {style="text-align: right"}
**Humose Perch-gley Podzol Soils**
:::

#### **ZPQ** {#sec-key-ZPQ .unnumbered}

Other soils with an [ortstein-pan](Diagnostics.qmd#sec-diag-opan).

::: {style="text-align: right"}
**Ortstein Perch-gley Podzol Soils**
:::

#### **ZPP** {#sec-key-ZPP .unnumbered}

Other soils that have a [placic horizon](Diagnostics.qmd#sec-diag-plac).

::: {style="text-align: right"}
**Placic Perch-gley Podzol Soils**
:::

#### **ZPT** {#sec-key-ZPT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Perch-gley Podzol Soils**
:::

### **ZG** - GROUNDWATER-GLEY PODZOL SOILS {#sec-ZG .unnumbered}

Groundwater-gley Podzol Soils occur in periodically or predominantly saturated sites (unless artificially drained) in which the wetness is indicated by brownish or reddish mottles or [peaty topsoils](Diagnostics.qmd#sec-diag-pts). The wetness is caused by a groundwater-table.

#### **ZGH** {#sec-key-ZGH .unnumbered}

Groundwater-gley Podzol Soils that have a Bh horizon thicker than 5 cm.

::: {style="text-align: right"}
**Humose Groundwater-gley Podzol Soils**
:::

#### **ZGT** {#sec-key-ZGT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Groundwater-gley Podzol Soils**
:::

### **ZX** - PAN PODZOL SOILS {#sec-ZX .unnumbered}

Pan Podzol Soils have layer with firm or greater unconfined strength over all moisture states, or are at least weakly indurated, which restricts the penetration of roots and reduces permeability.

#### **ZXU** {#sec-key-ZXU .unnumbered}

Pan Podzol Soils that have a [humus-pan](Diagnostics.qmd#sec-diag-hpan).

::: {style="text-align: right"}
**Humus-pan Pan Podzol Soils**
:::

#### **ZXJH** {#sec-key-ZXJH .unnumbered}

Other soils that have a Bh horizon that also have an [argillic horizon](Diagnostics.qmd#sec-diag-argh) beneath the [ortstein-pan](Diagnostics.qmd#sec-diag-opan) or [placic horizon](Diagnostics.qmd#sec-diag-plac).

::: {style="text-align: right"}
**Argillic-humose Pan Podzol Soils**
:::

#### **ZXH** {#sec-key-ZXH .unnumbered}

Other soils that have a Bh horizon that and either an [ortstein-pan](Diagnostics.qmd#sec-diag-opan) or [placic horizon](Diagnostics.qmd#sec-diag-plac).

::: {style="text-align: right"}
**Humose Pan Podzol Soils**
:::

#### **ZXX** {#sec-key-ZXX .unnumbered}

Other soils that have a [fragipan](Diagnostics.qmd#sec-diag-fpan).

::: {style="text-align: right"}
**Fragic Pan Podzol Soils**
:::

#### **ZXQ** {#sec-key-ZXQ .unnumbered}

Other soils that have an [ortstein-pan](Diagnostics.qmd#sec-diag-opan).

::: {style="text-align: right"}
**Ortstein Pan Podzol Soils**
:::

#### **ZXP** {#sec-key-ZXP .unnumbered}

Other soils that have a [placic horizon](Diagnostics.qmd#sec-diag-plac).

::: {style="text-align: right"}
**Placic Pan Podzol Soils**
:::

#### **ZXF** {#sec-key-ZXF .unnumbered}

Other soils.

::: {style="text-align: right"}
**Firm Pan Podzol Soils**
:::

### **ZO** - ORTHIC PODZOL SOILS {#sec-ZO .unnumbered}

Orthic Podzol Soils are usually well or moderately well drained, and do not have a pan or a firm horizon with massive structure.

#### **ZOJH** {#sec-key-ZOJH .unnumbered}

Other soils with an [argillic horizon](Diagnostics.qmd#sec-diag-argh) beneath a Bh horizon.

::: {style="text-align: right"}
**Argillic-humose Orthic Podzol Soils**
:::

#### **ZOH** {#sec-key-ZOH .unnumbered}

Orthic Podzol Soils with a Bh horizon thicker than 5 cm.

::: {style="text-align: right"}
**Humose Orthic Podzol Soils**
:::

#### **ZOT** {#sec-key-ZOT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Orthic Podzol Soils**
:::

{{< pagebreak >}}
