---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Raw Soils {#sec-ord-W}

## Concept of the Order {#sec-con-W}

Raw Soils lack a [distinct topsoil](Diagnostics.qmd#sec-diag-dts) or are fluid at a shallow depth. They occur in environments where the development of topsoils is prevented by rockiness, by active erosion, or deposition. They include beach sands, alpine rock areas, debris-mantles underlain by permafrost, active screes, lagoons and tidal estuaries.

## Correlation {#sec-cor-W}

Raw Soils correspond in part with very weakly developed recent soils of the *New Zealand Genetic Soil Classification*, and in part with materials that were often not considered to be soil. They are either Entisols or are unclassified in *Soil Taxonomy*.

## Occurrence {#sec-occ-W}

Raw Soils occur scattered throughout New Zealand, particularly in association with high mountains, braided rivers, beaches and tidal mudflats, steep scoria cones or very recently erupted or eroded andesitic tephras.

## Accessory Properties of the Order {#sec-acc-W}

1.  *No B horizons.* Pedogenetic horizons are lacking apart from a rudimentary topsoil.
2.  *Fresh or weakly weathered.* Coarse rock fragments and sand particles are generally without coatings, although coarse rock fragments in some screes may have weathering rinds.
3.  *Inherited mineralogy.* The soil mineralogy is very similar to that of the parent material and a range of mineralogy classes is therefore possible.
4.  *In soils with a fluid subsurface layer, a continuously high water-table is present.* The deposition of fresh sediment may occur.
5.  *Non-fluid soils occur in environments with active erosion or deposition.*
6.  *Low fertility.* Nitrogen in particular, is deficient.
7.  *Erosive.* Most materials are unaggregated and likely to be highly erosive.
8.  *Sparse vegetation.* Vegetation is either absent, sparse or patchy, often consisting of ephemeral herbaceous plants, mosses or lichens. Mangroves occur mainly on Raw Soils.

## Summary of Raw Soils Hierarchy {#sec-sum-W}

```{r}
#| label: tbl-W
#| tbl-cap: "Raw Soils"
#| classes: '.plain .hover'

library(gt)

table_W_dat <- data.frame(
  'Code' = c('WW', '', 'WG', rep('', 7), 'WH', 'WC', 'WX', 'WS', '', 'WF', 'WT', 'WO'),
  'Group' = c('Hydric', '', 'Gley', rep('', 7), 'Hydrothermal', 'Cryic', 'Rocky', 'Sandy', '',
              'Fluvial','Tephric', 'Orthic'),
  'Subgroup' = c('Sulfidic', 'Typic', 
                 'Sulfuric', 'Fluid-sulfidic', 'Sulfidic', 'Fluid-saline', 'Saline', 'Fluid', 'Sandy', 'Typic',
                 '-', '-', '-', 'Tephric', 'Typic', '-', '-', '-'),
  'Example_Series' = c('-', '-', '-', 'Takahiwai', '-', '-', 'Takahiwai', 'Paratai', '-', '-',
                       'Atiamuri', '-',
                       'Alpine', '-', 'Riverton', 'Selwyn', 'Tarawera', 'Alpine')
) 


table_W <- gt(table_W_dat) |>
  tab_options(
    column_labels.font.weight = 'bold', 
    heading.title.font.weight = 'bold',
    table.align = 'center',
    table.width = '95%'
  ) |>
  cols_label(Example_Series = 'Example Series') |>
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(columns = 1)) |>
  cols_width(Code ~pct(10),  Group ~pct(20), Subgroup ~pct(35))

table_W
```

## Key to Groups of Raw Soils {#sec-grp-W}

#### **WW** {#sec-key-WW .unnumbered}

Raw Soils with surface water present for a majority of the time (but not constantly).

::: {style="text-align: right"}
[**HYDRIC RAW SOILS**](#sec-WW)
:::

#### **WG** {#sec-key-WG .unnumbered}

Other Raw Soils that at 30 cm or less from the mineral soil surface have EITHER

1.  The upper boundary of a [reductimorphic horizon](Diagnostics.qmd#sec-diag-redmh), OR
2.  Sufficient active ferrous iron to give a positive reaction to [Childs' test](Diagnostics.qmd#sec-diag-fe2) at some time in the year, OR
3.  Are saturated for 30 or more consecutive days in most years.

::: {style="text-align: right"}
[**GLEY RAW SOILS**](#sec-WG)
:::

#### **WH** {#sec-key-WH .unnumbered}

Other Raw Soils that have mean annual soil temperature at 30 cm depth of at least 2.5°C more than the mean annual air temperature.

::: {style="text-align: right"}
[**HYDROTHERMAL RAW SOILS**](#sec-WH)
:::

#### **WC** {#sec-key-WC .unnumbered}

Other Raw Soils with a permafrost or evidence of cryoturbation within 1 m of the soil surface.

::: {style="text-align: right"}
[**CRYIC RAW SOILS**](#sec-WC)
:::

#### **WX** {#sec-key-WX .unnumbered}

Other Raw Soils with a [lithic](Diagnostics.qmd#sec-diag-lithc) or [paralithic contact](Diagnostics.qmd#sec-diag-lithp) within 30 cm of the soil surface.

::: {style="text-align: right"}
[**ROCKY RAW SOILS**](#sec-WX)
:::

#### **WS** {#sec-key-WS .unnumbered}

Other Raw Soils that have sand or loamy sand texture and that have less than 35% coarse rock fragments (by volume) in all horizons, from the soil surface to 60 cm depth or more.

::: {style="text-align: right"}
[**SANDY RAW SOILS**](#sec-WS)
:::

#### **WF** {#sec-key-WF .unnumbered}

Other Raw Soils that have [fluvial features](Diagnostics.qmd#sec-diag-fluv) and are not buried by more than 30 cm of material without [fluvial features](Diagnostics.qmd#sec-diag-fluv).

::: {style="text-align: right"}
[**FLUVIAL RAW SOILS**](#sec-WF)
:::

#### **WT** {#sec-key-WT .unnumbered}

Other Raw Soils in [tephric soil material](Diagnostics.qmd#sec-diag-teph) from the soil surface to 30 cm depth or more.

::: {style="text-align: right"}
[**TEPHRIC RAW SOILS**](#sec-WT)
:::

#### **WO** {#sec-key-WO .unnumbered}

Other Raw Soils.

::: {style="text-align: right"}
[**ORTHIC RAW SOILS**](#sec-WO)
:::

## Key to Subgroups of Raw Soils {#sec-sub-W .unnumbered}

### **WW** - HYDRIC RAW SOILS {#sec-WW .unnumbered}

Hydric Raw Soils have surface water present for a majority of the time, but not always. They are commonly part of an active riverbed or other shore environment (coastal, lakes).

#### **WWU** {#sec-key-WWU .unnumbered}

Hydric Raw Soils in which [sulfidic soil material](Diagnostics.qmd#sec-diag-sulfd) is present in some part within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Sulfidic Hydric Raw Soils**
:::

#### **WWT** {#sec-key-WWT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Hydric Raw Soils**
:::

### **WG** - GLEY RAW SOILS {#sec-WG .unnumbered}

Gley Raw Soils occur in sites that are periodically or permanently flooded. Wetness is expressed in the soil by [low-chroma colours](Diagnostics.qmd#sec-diag-lch) with brownish or reddish mottles, by water saturation or is indicated by a chemical test for the presence of reduced iron ([Childs' test](Diagnostics.qmd#sec-diag-fe2)).

#### **WGR** {#sec-key-WGR .unnumbered}

Gley Raw Soils in which [sulfuric soil material](Diagnostics.qmd#sec-diag-sulfr) is present in some part within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Sulfuric Gley Raw Soils**
:::

#### **WGFU** {#sec-key-WGFU .unnumbered}

Other soils that have BOTH

1.  Moderately fluid or very fluid fluidity class at a depth of 30 cm or less, AND
2.  [Sulfidic soil material](Diagnostics.qmd#sec-diag-sulfd) is present in some part within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Fluid-sulfidic Gley Raw Soils**
:::

#### **WGU** {#sec-key-WGU .unnumbered}

Other soils in which [sulfidic soil material](Diagnostics.qmd#sec-diag-sulfd) is present in some part within 90 cm of the mineral soil surface.

::: {style="text-align: right"}
**Sulfidic Gley Raw Soils**
:::

#### **WGFQ** {#sec-key-WGFQ .unnumbered}

Other soils that within 30 cm of the mineral soil surface have BOTH

1.  Moderately fluid or very fluid fluidity class, AND
2.  [Saline soil material](Diagnostics.qmd#sec-diag-salt).

::: {style="text-align: right"}
**Fluid-saline Gley Raw Soils**
:::

#### **WGQ** {#sec-key-WGQ .unnumbered}

Other soils that within 30 cm of the mineral soil surface have [saline soil material](Diagnostics.qmd#sec-diag-salt).

::: {style="text-align: right"}
**Saline Gley Raw Soils**
:::

#### **WGF** {#sec-key-WGF .unnumbered}

Other soils that within 30 cm of the mineral soil surface have moderately fluid or very fluid fluidity class.

::: {style="text-align: right"}
**Fluid Gley Raw Soils**
:::

#### **WGS** {#sec-key-WGS .unnumbered}

Other soils that have sand or loamy sand texture, and that have less than 35% coarse rock fragments (by volume) in all horizons, from the soil surface to 60 cm depth or more.

::: {style="text-align: right"}
**Sandy Gley Raw Soils**
:::

#### **WGT** {#sec-key-WGT .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Gley Raw Soils**
:::

### **WH** - HYDROTHERMAL RAW SOILS {#sec-WH .unnumbered}

Hydrothermal Raw Soils occur in active hydrothermal areas affected by hot liquids or steam.

No subgroups have been defined.

### **WX** - ROCKY RAW SOILS {#sec-WX .unnumbered}

Rocky Raw Soils occur on rock outcrops subject to erosion. The soil volume available to roots is severely restricted.

No subgroups have been defined.

### **WS** - SANDY RAW SOILS {#sec-WS .unnumbered}

Sandy Raw Soils occur in areas of active erosion, transportation and deposition of sand, most commonly as dune sands.

#### **WSK** {#sec-key-WSK .unnumbered}

Sandy Raw Soils containing [tephric soil material](Diagnostics.qmd#sec-diag-teph) from the soil surface to 30 cm depth or more.

::: {style="text-align: right"}
**Tephric Sandy Raw Soils**
:::

#### **WST** {#sec-key-WST .unnumbered}

Other soils.

::: {style="text-align: right"}
**Typic Sandy Raw Soils**
:::

### **WF** - FLUVIAL RAW SOILS {#sec-WF .unnumbered}

Fluvial Raw Soils occur in sediments deposited by flowing water. They occur on land surfaces on which there is a high risk of flooding.

No subgroups have been defined.

### **WT** - TEPHRIC RAW SOILS {#sec-WT .unnumbered}

Tephric Raw Soils occur in unconsolidated deposits of pyroclastic origin, predominantly basaltic scoriae, with potentially minor additions of rhyolitic to andesitic pyroclastic material. 

No subgroups have been defined.

### **WO** - ORTHIC RAW SOILS {#sec-WO .unnumbered}

Orthic Raw Soils occur in land that is being eroded, on rock outcrops or land that has received sediment emplaced primarily by slope processes, including debris-mantled slopes in alpine areas.

No subgroups have been defined.

{{< pagebreak >}}
